-- ACCESS_EVENT persistence table for observability writes
-- Generated on 2026-04-15 to backfill production DB where ACCESS_EVENT is missing.

CREATE TABLE ACCESS_EVENT (
    EVENT_ID VARCHAR(40) NOT NULL,
    PROJECT_ID VARCHAR(80),
    TRACE_ID VARCHAR(40),
    REQUEST_ID VARCHAR(40),
    PAGE_ID VARCHAR(100),
    API_ID VARCHAR(200),
    REQUEST_URI VARCHAR(500) NOT NULL,
    HTTP_METHOD VARCHAR(16) NOT NULL,
    FEATURE_TYPE VARCHAR(40),
    ACTOR_ID VARCHAR(60),
    ACTOR_TYPE VARCHAR(30),
    ACTOR_ROLE VARCHAR(60),
    ACTOR_INSTT_ID VARCHAR(60),
    COMPANY_CONTEXT_ID VARCHAR(60),
    TARGET_COMPANY_CONTEXT_ID VARCHAR(60),
    REMOTE_ADDR VARCHAR(64),
    RESPONSE_STATUS INTEGER,
    DURATION_MS INTEGER,
    REQUEST_CONTENT_TYPE VARCHAR(120),
    "QUERY_STRING" VARCHAR(2000),
    PARAMETER_SUMMARY CLOB,
    ERROR_MESSAGE VARCHAR(2000),
    COMPANY_SCOPE_DECISION VARCHAR(120),
    COMPANY_SCOPE_REASON VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_ACCESS_EVENT_TRACE_ID ON ACCESS_EVENT (TRACE_ID);
CREATE INDEX IDX_ACCESS_EVENT_PROJECT_ID ON ACCESS_EVENT (PROJECT_ID);
CREATE INDEX IDX_ACCESS_EVENT_PAGE_ID ON ACCESS_EVENT (PAGE_ID);
CREATE INDEX IDX_ACCESS_EVENT_API_ID ON ACCESS_EVENT (API_ID);
CREATE INDEX IDX_ACCESS_EVENT_ACTOR_ID ON ACCESS_EVENT (ACTOR_ID);
CREATE INDEX IDX_ACCESS_EVENT_ACTOR_INSTT_ID ON ACCESS_EVENT (ACTOR_INSTT_ID);
CREATE INDEX IDX_ACCESS_EVENT_PROJECT_INSTT ON ACCESS_EVENT (PROJECT_ID, ACTOR_INSTT_ID);
CREATE INDEX IDX_ACCESS_EVENT_CREATED_AT ON ACCESS_EVENT (CREATED_AT);
