-- CUBRID-safe admin new page menu registration
-- AI workbench group: A19001
-- New page code: A1900106

SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A19001', 'A1900106')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A19001', 'A1900106')
   OR MENU_URL = '/admin/system/new-page'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'A1900106_VIEW';

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A1900106', '새 페이지', 'New Page', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A1900106'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A1900106', '새 페이지', 'New Page', '/admin/system/new-page', 'note_stack', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A1900106'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '새 페이지',
    MENU_NM_EN = 'New Page',
    MENU_URL = '/admin/system/new-page',
    MENU_ICON = 'note_stack',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A1900106';

INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A1900106', 6, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A1900106'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 6,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A1900106';

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A1900106', 'A1900106_VIEW', '새 페이지 조회', 'View New Page', '새 페이지 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A1900106_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A1900106',
    FEATURE_NM = '새 페이지 조회',
    FEATURE_NM_EN = 'View New Page',
    FEATURE_DC = '새 페이지 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A1900106_VIEW';

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'A1900106_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'A1900102_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'A1900106_VIEW'
  );

SELECT
    m.MENU_CODE,
    m.MENU_NM,
    m.MENU_URL,
    o.SORT_ORDR,
    f.FEATURE_CODE,
    f.FEATURE_NM
FROM COMTNMENUINFO m
LEFT JOIN COMTNMENUORDER o
  ON o.MENU_CODE = m.MENU_CODE
LEFT JOIN COMTNMENUFUNCTIONINFO f
  ON f.MENU_CODE = m.MENU_CODE
WHERE m.MENU_CODE = 'A1900106';
