-- Version and Deploy Governance rollback
-- Generated on 2026-04-17

DROP INDEX IDX_RDT_STATUS;
DROP INDEX IDX_RDT_PACKAGE_ENV;
DROP INDEX IDX_RRP_BUILD_RUN;
DROP INDEX IDX_RRP_RELEASE_UNIT;
DROP INDEX IDX_RRU_VERSION;
DROP INDEX IDX_RRU_PROJECT_STATUS;

DROP TABLE RSN_DEPLOY_TRACE;
DROP TABLE RSN_RUNTIME_PACKAGE;
DROP TABLE RSN_RELEASE_UNIT;
