-- Carbonet builder overlay and compatibility control-plane extension
-- Generated on 2026-03-24
-- Target DB: CUBRID-compatible SQL draft

CREATE TABLE BUILDER_OVERLAY_REGISTRY (
    OVERLAY_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    PAGE_ID VARCHAR(100),
    SCENARIO_ID VARCHAR(80),
    GUIDED_STATE_ID VARCHAR(80) NOT NULL,
    SCREEN_FAMILY_RULE_ID VARCHAR(80) NOT NULL,
    TEMPLATE_LINE_ID VARCHAR(80) NOT NULL,
    OWNER_LANE VARCHAR(40) NOT NULL,
    OVERLAY_TYPE VARCHAR(60) NOT NULL,
    TARGET_SCOPE VARCHAR(40) NOT NULL,
    TARGET_KEY_JSON VARCHAR(4000) NOT NULL,
    PAYLOAD_SCHEMA_VERSION VARCHAR(40) NOT NULL,
    MATCH_POLICY VARCHAR(60) NOT NULL,
    APPLY_MODE VARCHAR(60) NOT NULL,
    OVERLAY_VERSION VARCHAR(40) NOT NULL,
    APPROVAL_STATE VARCHAR(30) NOT NULL,
    OVERLAY_STATUS VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(60),
    UPDATED_BY VARCHAR(60),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (OVERLAY_ID)
);

CREATE INDEX IDX_BUILDER_OVERLAY_PROJECT_ID ON BUILDER_OVERLAY_REGISTRY (PROJECT_ID);
CREATE INDEX IDX_BUILDER_OVERLAY_PAGE_ID ON BUILDER_OVERLAY_REGISTRY (PAGE_ID);
CREATE INDEX IDX_BUILDER_OVERLAY_TYPE ON BUILDER_OVERLAY_REGISTRY (OVERLAY_TYPE);

CREATE TABLE BUILDER_OVERLAY_PAYLOAD_REVISION (
    OVERLAY_REVISION_ID VARCHAR(80) NOT NULL,
    OVERLAY_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    REVISION_NO INTEGER NOT NULL,
    PARENT_OVERLAY_REVISION_ID VARCHAR(80),
    PAYLOAD_JSON VARCHAR(16000) NOT NULL,
    PAYLOAD_HASH VARCHAR(128) NOT NULL,
    VALIDATION_SUMMARY VARCHAR(4000),
    COMPATIBILITY_RANGE VARCHAR(200),
    EDITOR_TYPE VARCHAR(30) NOT NULL,
    EDITOR_ID VARCHAR(60),
    AGENT_PROVIDER VARCHAR(80),
    AGENT_MODEL VARCHAR(120),
    AGENT_SESSION_ID VARCHAR(120),
    APPROVAL_STATE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (OVERLAY_REVISION_ID)
);

CREATE INDEX IDX_BUILDER_OVERLAY_REV_OVERLAY_ID ON BUILDER_OVERLAY_PAYLOAD_REVISION (OVERLAY_ID);
CREATE INDEX IDX_BUILDER_OVERLAY_REV_PROJECT_ID ON BUILDER_OVERLAY_PAYLOAD_REVISION (PROJECT_ID);

CREATE TABLE BUILDER_OVERLAY_SET (
    OVERLAY_SET_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    OVERLAY_SET_NAME VARCHAR(200) NOT NULL,
    TARGET_RELEASE_UNIT_ID VARCHAR(80),
    OVERLAY_HASH VARCHAR(128) NOT NULL,
    APPROVAL_STATE VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(60),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (OVERLAY_SET_ID)
);

CREATE INDEX IDX_BUILDER_OVERLAY_SET_PROJECT_ID ON BUILDER_OVERLAY_SET (PROJECT_ID);

CREATE TABLE BUILDER_OVERLAY_SET_ITEM (
    OVERLAY_SET_ITEM_ID VARCHAR(80) NOT NULL,
    OVERLAY_SET_ID VARCHAR(80) NOT NULL,
    OVERLAY_ID VARCHAR(80) NOT NULL,
    OVERLAY_REVISION_ID VARCHAR(80) NOT NULL,
    APPLY_ORDER INTEGER DEFAULT 0 NOT NULL,
    REQUIRED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    PRIMARY KEY (OVERLAY_SET_ITEM_ID)
);

CREATE INDEX IDX_BUILDER_OVERLAY_SET_ITEM_SET_ID ON BUILDER_OVERLAY_SET_ITEM (OVERLAY_SET_ID);
CREATE INDEX IDX_BUILDER_OVERLAY_SET_ITEM_OVERLAY_ID ON BUILDER_OVERLAY_SET_ITEM (OVERLAY_ID);

CREATE TABLE BUILDER_COMPATIBILITY_DECLARATION (
    COMPATIBILITY_DECLARATION_ID VARCHAR(80) NOT NULL,
    BUILDER_VERSION VARCHAR(40) NOT NULL,
    BUILDER_RULE_PACK_VERSION VARCHAR(40) NOT NULL,
    TEMPLATE_PACK_VERSION VARCHAR(40) NOT NULL,
    SUPPORTED_SOURCE_CONTRACT_RANGE VARCHAR(200) NOT NULL,
    SUPPORTED_OVERLAY_SCHEMA_RANGE VARCHAR(200) NOT NULL,
    EMITTED_MANIFEST_CONTRACT_VERSION VARCHAR(40) NOT NULL,
    EMITTED_AUTHORITY_CONTRACT_VERSION VARCHAR(40) NOT NULL,
    RELEASE_COMPATIBILITY_VERSION VARCHAR(40) NOT NULL,
    BREAKING_CHANGE_YN CHAR(1) DEFAULT 'N' NOT NULL,
    COMPATIBILITY_VERDICT VARCHAR(30) NOT NULL,
    REVIEWED_BY VARCHAR(60),
    REVIEWED_AT DATETIME,
    STATUS VARCHAR(30) NOT NULL,
    PRIMARY KEY (COMPATIBILITY_DECLARATION_ID)
);

CREATE INDEX IDX_BUILDER_COMP_DECL_BUILDER_VERSION ON BUILDER_COMPATIBILITY_DECLARATION (BUILDER_VERSION);

CREATE TABLE BUILDER_MIGRATION_PLAN (
    MIGRATION_PLAN_ID VARCHAR(80) NOT NULL,
    FROM_BUILDER_VERSION VARCHAR(40) NOT NULL,
    TO_BUILDER_VERSION VARCHAR(40) NOT NULL,
    FROM_SOURCE_CONTRACT_RANGE VARCHAR(200) NOT NULL,
    TO_SOURCE_CONTRACT_RANGE VARCHAR(200) NOT NULL,
    FROM_OVERLAY_SCHEMA_RANGE VARCHAR(200) NOT NULL,
    TO_OVERLAY_SCHEMA_RANGE VARCHAR(200) NOT NULL,
    REQUIRED_TRANSFORM_SET_JSON VARCHAR(8000),
    NON_TRANSFORMABLE_FIELD_SET_JSON VARCHAR(4000),
    MANUAL_REVIEW_REQUIRED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_BY VARCHAR(60),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (MIGRATION_PLAN_ID)
);

CREATE INDEX IDX_BUILDER_MIGRATION_FROM_TO ON BUILDER_MIGRATION_PLAN (FROM_BUILDER_VERSION, TO_BUILDER_VERSION);

CREATE TABLE BUILDER_COMPATIBILITY_CHECK_RUN (
    COMPATIBILITY_CHECK_RUN_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    BUILDER_VERSION VARCHAR(40) NOT NULL,
    BUILDER_RULE_PACK_VERSION VARCHAR(40) NOT NULL,
    TEMPLATE_PACK_VERSION VARCHAR(40) NOT NULL,
    SOURCE_CONTRACT_VERSION VARCHAR(40) NOT NULL,
    OVERLAY_SCHEMA_VERSION VARCHAR(40),
    OVERLAY_SET_ID VARCHAR(80),
    MIGRATION_PLAN_ID VARCHAR(80),
    CHECK_SCOPE VARCHAR(40) NOT NULL,
    COMPATIBILITY_VERDICT VARCHAR(30) NOT NULL,
    BLOCKING_ISSUE_COUNT INTEGER DEFAULT 0 NOT NULL,
    STARTED_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME,
    REQUESTED_BY VARCHAR(60),
    PRIMARY KEY (COMPATIBILITY_CHECK_RUN_ID)
);

CREATE INDEX IDX_BUILDER_COMP_CHECK_RUN_PROJECT_ID ON BUILDER_COMPATIBILITY_CHECK_RUN (PROJECT_ID);
CREATE INDEX IDX_BUILDER_COMP_CHECK_RUN_VERDICT ON BUILDER_COMPATIBILITY_CHECK_RUN (COMPATIBILITY_VERDICT);

CREATE TABLE BUILDER_COMPATIBILITY_CHECK_RESULT (
    COMPATIBILITY_RESULT_ID VARCHAR(80) NOT NULL,
    COMPATIBILITY_CHECK_RUN_ID VARCHAR(80) NOT NULL,
    RESULT_TYPE VARCHAR(40) NOT NULL,
    TARGET_SCOPE VARCHAR(40),
    TARGET_KEY VARCHAR(300),
    SEVERITY VARCHAR(20) NOT NULL,
    RULE_CODE VARCHAR(80) NOT NULL,
    SUMMARY VARCHAR(1000) NOT NULL,
    DETAILS_JSON VARCHAR(8000),
    BLOCKING_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (COMPATIBILITY_RESULT_ID)
);

CREATE INDEX IDX_BUILDER_COMP_RESULT_RUN_ID ON BUILDER_COMPATIBILITY_CHECK_RESULT (COMPATIBILITY_CHECK_RUN_ID);
