-- Notification center history storage
--
-- Purpose:
-- - persist delivery history and operator activity as append-only rows
-- - support server-side count/list pagination without rewriting snapshot JSON
-- - allow legacy snapshot fallback until every environment applies this DDL

CREATE TABLE COMTNADMINNOTIFICATIONDELIVERYHIST (
    DELIVERY_ID VARCHAR(40) NOT NULL,
    SENT_AT DATETIME DEFAULT CURRENT_DATETIME,
    ACTOR_USER_ID VARCHAR(60),
    DELIVERY_MODE VARCHAR(40),
    FINDING_COUNT INTEGER DEFAULT 0,
    SLACK_ENABLED CHAR(1) DEFAULT 'N',
    MAIL_ENABLED CHAR(1) DEFAULT 'N',
    WEBHOOK_ENABLED CHAR(1) DEFAULT 'N',
    SLACK_CHANNEL VARCHAR(200),
    MAIL_RECIPIENTS VARCHAR(1000),
    WEBHOOK_URL VARCHAR(1000),
    DELIVERY_STATUS VARCHAR(40),
    TOP_FINDING VARCHAR(1000),
    DELIVERY_DETAIL VARCHAR(4000),
    SLACK_STATUS VARCHAR(40),
    MAIL_STATUS VARCHAR(40),
    WEBHOOK_STATUS VARCHAR(40),
    USE_AT CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (DELIVERY_ID)
);

CREATE INDEX IDX_NOTI_DELIVERY_01 ON COMTNADMINNOTIFICATIONDELIVERYHIST (SENT_AT DESC);
CREATE INDEX IDX_NOTI_DELIVERY_02 ON COMTNADMINNOTIFICATIONDELIVERYHIST (DELIVERY_MODE, DELIVERY_STATUS, SENT_AT DESC);

CREATE TABLE COMTNADMINNOTIFICATIONACTIVITYHIST (
    ACTIVITY_ID VARCHAR(40) NOT NULL,
    HAPPENED_AT DATETIME DEFAULT CURRENT_DATETIME,
    ACTION_CODE VARCHAR(60),
    ACTOR_USER_ID VARCHAR(60),
    TARGET_TEXT VARCHAR(1000),
    DETAIL_TEXT VARCHAR(4000),
    SOURCE_TYPE VARCHAR(40),
    USE_AT CHAR(1) DEFAULT 'Y',
    PRIMARY KEY (ACTIVITY_ID)
);

CREATE INDEX IDX_NOTI_ACTIVITY_01 ON COMTNADMINNOTIFICATIONACTIVITYHIST (HAPPENED_AT DESC);
CREATE INDEX IDX_NOTI_ACTIVITY_02 ON COMTNADMINNOTIFICATIONACTIVITYHIST (ACTION_CODE, HAPPENED_AT DESC);
