-- Carbonet System Asset Lifecycle Workflow Schema
-- Generated on 2026-04-15

-- 1. 자산 생명주기 계획 (Lifecycle Plans)
CREATE TABLE SYSTEM_ASSET_LIFECYCLE_PLAN (
    PLAN_ID VARCHAR(120) NOT NULL,
    ASSET_ID VARCHAR(120) NOT NULL,
    TARGET_STAGE VARCHAR(20) NOT NULL, -- CREATE, PUBLISH, DEPRECATE, RETIRE
    PLAN_STATUS VARCHAR(20) NOT NULL, -- DRAFT, PENDING, APPROVED, REJECTED, COMPLETED
    REQUESTER_ID VARCHAR(50),
    APPROVER_ID VARCHAR(50),
    TARGET_DATE DATETIME,
    REASON CLOB,
    CREATED_AT DATETIME DEFAULT CURRENT_DATETIME,
    UPDATED_AT DATETIME DEFAULT CURRENT_DATETIME,
    PRIMARY KEY (PLAN_ID)
);

-- 2. 자산 생명주기 증적 (Lifecycle Evidence)
CREATE TABLE SYSTEM_ASSET_LIFECYCLE_EVIDENCE (
    EVIDENCE_ID VARCHAR(120) NOT NULL,
    PLAN_ID VARCHAR(120) NOT NULL,
    CHECKPOINT_KEY VARCHAR(50) NOT NULL, -- e.g., 'IMPACT_REVIEW', 'BACKUP_CONFIRM'
    EVIDENCE_TYPE VARCHAR(20), -- LINK, TEXT, JSON
    EVIDENCE_VALUE CLOB,
    VERIFIED_BY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT CURRENT_DATETIME,
    PRIMARY KEY (EVIDENCE_ID)
);

CREATE INDEX IDX_ASSET_PLAN_ASSET ON SYSTEM_ASSET_LIFECYCLE_PLAN (ASSET_ID);
CREATE INDEX IDX_ASSET_PLAN_STATUS ON SYSTEM_ASSET_LIFECYCLE_PLAN (PLAN_STATUS);
