-- CUBRID-safe DB sync deploy console registration
-- Parent tree: A006 (시스템) > A00604 (백업)
-- New page: A0060406 (DB 동기화 배포)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00604', 'A0060406')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00604', 'A0060406')
   OR MENU_URL = '/admin/system/db-sync-deploy'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0060406_VIEW',
    'A0060406_ANALYZE',
    'A0060406_EXECUTE',
    'A0060406_BREAKGLASS'
)
ORDER BY FEATURE_CODE;

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A00604', '백업', 'Backup', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A00604'
);

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0060406', 'DB 동기화 배포', 'DB Sync Deploy', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0060406'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = 'DB 동기화 배포',
    CODE_DC = 'DB Sync Deploy',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0060406';

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A00604', '백업', 'Backup', '#', 'backup', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A00604'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 'DB 동기화 배포', 'DB Sync Deploy', '/admin/system/db-sync-deploy', 'published_with_changes', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0060406'
);

UPDATE COMTNMENUINFO
SET MENU_NM = 'DB 동기화 배포',
    MENU_NM_EN = 'DB Sync Deploy',
    MENU_URL = '/admin/system/db-sync-deploy',
    MENU_ICON = 'published_with_changes',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060406';

INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 6, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0060406'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 6,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060406';

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 'A0060406_VIEW', 'DB 동기화 배포 조회', 'View DB Sync Deploy', 'DB 동기화 배포 콘솔 조회 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060406_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 'A0060406_ANALYZE', 'DB 반영 사전 점검', 'Analyze DB Sync Deploy', 'DB 동기화 전 정책 및 diff 사전 점검 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060406_ANALYZE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 'A0060406_EXECUTE', 'DB 동기화 배포 실행', 'Execute DB Sync Deploy', '승인된 DB 동기화 및 fresh deploy 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060406_EXECUTE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060406', 'A0060406_BREAKGLASS', '긴급 우회 실행', 'Run Breakglass DB Sync Deploy', '긴급 우회 전용 DB 동기화 배포 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060406_BREAKGLASS'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060406',
    FEATURE_NM = 'DB 동기화 배포 조회',
    FEATURE_NM_EN = 'View DB Sync Deploy',
    FEATURE_DC = 'DB 동기화 배포 콘솔 조회 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060406_VIEW';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060406',
    FEATURE_NM = 'DB 반영 사전 점검',
    FEATURE_NM_EN = 'Analyze DB Sync Deploy',
    FEATURE_DC = 'DB 동기화 전 정책 및 diff 사전 점검 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060406_ANALYZE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060406',
    FEATURE_NM = 'DB 동기화 배포 실행',
    FEATURE_NM_EN = 'Execute DB Sync Deploy',
    FEATURE_DC = '승인된 DB 동기화 및 fresh deploy 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060406_EXECUTE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060406',
    FEATURE_NM = '긴급 우회 실행',
    FEATURE_NM_EN = 'Run Breakglass DB Sync Deploy',
    FEATURE_DC = '긴급 우회 전용 DB 동기화 배포 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060406_BREAKGLASS';

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_MASTER', 'A0060406_VIEW', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_MASTER' AND FEATURE_CODE = 'A0060406_VIEW'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_MASTER', 'A0060406_ANALYZE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_MASTER' AND FEATURE_CODE = 'A0060406_ANALYZE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_MASTER', 'A0060406_EXECUTE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_MASTER' AND FEATURE_CODE = 'A0060406_EXECUTE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_MASTER', 'A0060406_BREAKGLASS', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_MASTER' AND FEATURE_CODE = 'A0060406_BREAKGLASS'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_ADMIN', 'A0060406_VIEW', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_ADMIN' AND FEATURE_CODE = 'A0060406_VIEW'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_ADMIN', 'A0060406_ANALYZE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_ADMIN' AND FEATURE_CODE = 'A0060406_ANALYZE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_ADMIN', 'A0060406_EXECUTE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_ADMIN' AND FEATURE_CODE = 'A0060406_EXECUTE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_SYSTEM_ADMIN', 'A0060406_BREAKGLASS', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_SYSTEM_ADMIN' AND FEATURE_CODE = 'A0060406_BREAKGLASS'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_OPERATION_ADMIN', 'A0060406_VIEW', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_OPERATION_ADMIN' AND FEATURE_CODE = 'A0060406_VIEW'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_OPERATION_ADMIN', 'A0060406_ANALYZE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_OPERATION_ADMIN' AND FEATURE_CODE = 'A0060406_ANALYZE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_OPERATION_ADMIN', 'A0060406_EXECUTE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_OPERATION_ADMIN' AND FEATURE_CODE = 'A0060406_EXECUTE'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_ADMIN', 'A0060406_VIEW', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_ADMIN' AND FEATURE_CODE = 'A0060406_VIEW'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_ADMIN', 'A0060406_ANALYZE', 'Y', CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE
    WHERE AUTHOR_CODE = 'ROLE_ADMIN' AND FEATURE_CODE = 'A0060406_ANALYZE'
);

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00604', 'A0060406')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00604', 'A0060406')
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0060406_VIEW',
    'A0060406_ANALYZE',
    'A0060406_EXECUTE',
    'A0060406_BREAKGLASS'
)
ORDER BY FEATURE_CODE;
