-- CUBRID-safe scheduler menu registration
-- Parent top: A006 (System)
-- New group: A00605 (Scheduler)
-- New page: A0060501 (Cron / Scheduler Management)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00605', 'A0060501')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00605', 'A0060501')
   OR MENU_URL = '/admin/system/scheduler'
ORDER BY MENU_CODE;

SELECT FEATURE_CODE, MENU_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'A0060501_VIEW';

-- Detail codes
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A00605', '스케줄러', 'Scheduler', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A00605'
);

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060501', '크론/스케줄러 관리', 'Cron / Scheduler Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0060501'
);

-- Menu info
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A00605', '스케줄러', 'Scheduler', '#', 'schedule', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A00605'
);

INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060501', '크론/스케줄러 관리', 'Cron / Scheduler Management', '/admin/system/scheduler', 'schedule_send', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0060501'
);

-- Menu order
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A00605', 5, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A00605'
);

INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060501', 1, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0060501'
);

-- View feature
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060501', 'A0060501_VIEW', '크론/스케줄러 관리 조회', 'Cron / Scheduler Management View', '크론/스케줄러 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060501_VIEW'
);

-- Author relations copied from security operations baseline
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060501_VIEW', 'N', CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'A0060201_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'A0060501_VIEW'
  );

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00605', 'A0060501')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00605', 'A0060501')
ORDER BY MENU_CODE;

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE IN ('A00605', 'A0060501')
ORDER BY MENU_CODE;

SELECT FEATURE_CODE, MENU_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'A0060501_VIEW';

SELECT AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE = 'A0060501_VIEW'
ORDER BY AUTHOR_CODE;
