CREATE TABLE PROJECT_DEPLOYMENT_HISTORY (
    DEPLOYMENT_HISTORY_ID VARCHAR(80) PRIMARY KEY,
    PROJECT_ID            VARCHAR(80) NOT NULL,
    RELEASE_VERSION       VARCHAR(80) NOT NULL,
    RELEASE_TITLE         VARCHAR(200),
    RELEASE_CONTENT       VARCHAR(4000),
    STATUS                VARCHAR(30) NOT NULL,
    SERVER_TARGET         VARCHAR(200),
    RELEASE_UNIT_ID       VARCHAR(120),
    DEPLOY_TRACE_ID       VARCHAR(120),
    GIT_COMMIT_SHA        VARCHAR(80),
    RESULT_MESSAGE        VARCHAR(1000),
    STARTED_AT            DATETIME NOT NULL,
    FINISHED_AT           DATETIME,
    UPDATED_AT            DATETIME NOT NULL,
    CREATED_BY            VARCHAR(80)
);

CREATE INDEX IX_PROJECT_DEPLOYMENT_HISTORY_PROJECT
    ON PROJECT_DEPLOYMENT_HISTORY (PROJECT_ID, STARTED_AT);
