-- Blocklist persistence schema
-- Apply before using the DB-backed /admin/system/blocklist page as the primary source.

CREATE TABLE COMTNBLOCKLISTENTRY (
    BLOCK_ID            VARCHAR(64)   NOT NULL,
    TARGET              VARCHAR(255)  NOT NULL,
    BLOCK_TYPE          VARCHAR(32)   NOT NULL,
    REASON              VARCHAR(1000) NOT NULL,
    REASON_EN           VARCHAR(1000),
    STATUS              VARCHAR(32)   NOT NULL,
    EXPIRES_AT          DATETIME,
    OWNER               VARCHAR(255),
    OWNER_EN            VARCHAR(255),
    SOURCE              VARCHAR(32)   NOT NULL,
    SOURCE_TITLE        VARCHAR(500),
    SOURCE_FINGERPRINT  VARCHAR(255),
    SOURCE_SEVERITY     VARCHAR(32),
    REGISTERED_AT       DATETIME      NOT NULL,
    ACTIVATED_AT        DATETIME,
    ACTIVATED_BY        VARCHAR(255),
    REVIEWED_AT         DATETIME,
    REVIEWED_BY         VARCHAR(255),
    LAST_ACTION_AT      DATETIME      NOT NULL,
    LAST_ACTION_BY      VARCHAR(255),
    USE_AT              CHAR(1)       DEFAULT 'Y' NOT NULL,
    FRST_REGISTER_ID    VARCHAR(64),
    FRST_REGIST_PNTTM   DATETIME      DEFAULT CURRENT_DATETIME NOT NULL,
    LAST_UPDUSR_ID      VARCHAR(64),
    LAST_UPDT_PNTTM     DATETIME      DEFAULT CURRENT_DATETIME NOT NULL,
    PRIMARY KEY (BLOCK_ID)
);

CREATE INDEX IDX_COMTNBLOCKLISTENTRY_STATUS
    ON COMTNBLOCKLISTENTRY (STATUS, SOURCE, USE_AT);

CREATE INDEX IDX_COMTNBLOCKLISTENTRY_TARGET
    ON COMTNBLOCKLISTENTRY (TARGET, BLOCK_TYPE, USE_AT);

CREATE TABLE COMTNBLOCKLISTACTIONHIST (
    ACTION_ID           VARCHAR(128)  NOT NULL,
    BLOCK_ID            VARCHAR(64)   NOT NULL,
    TARGET              VARCHAR(255)  NOT NULL,
    ACTION_TYPE         VARCHAR(32)   NOT NULL,
    STATUS              VARCHAR(32)   NOT NULL,
    DETAIL              VARCHAR(2000),
    DETAIL_EN           VARCHAR(2000),
    ACTOR_ID            VARCHAR(255),
    ACTOR_NAME          VARCHAR(255),
    SOURCE              VARCHAR(32)   NOT NULL,
    ACTION_AT           DATETIME      NOT NULL,
    EXPIRES_AT          DATETIME,
    USE_AT              CHAR(1)       DEFAULT 'Y' NOT NULL,
    FRST_REGISTER_ID    VARCHAR(64),
    FRST_REGIST_PNTTM   DATETIME      DEFAULT CURRENT_DATETIME NOT NULL,
    LAST_UPDUSR_ID      VARCHAR(64),
    LAST_UPDT_PNTTM     DATETIME      DEFAULT CURRENT_DATETIME NOT NULL,
    PRIMARY KEY (ACTION_ID)
);

CREATE INDEX IDX_COMTNBLOCKLISTACTIONHIST_BLOCK
    ON COMTNBLOCKLISTACTIONHIST (BLOCK_ID, ACTION_AT, USE_AT);

ALTER TABLE COMTNBLOCKLISTACTIONHIST
    ADD CONSTRAINT FK_COMTNBLOCKLISTACTIONHIST_ENTRY
    FOREIGN KEY (BLOCK_ID) REFERENCES COMTNBLOCKLISTENTRY (BLOCK_ID);

-- Optional seed rows matching the current migration UI.
INSERT INTO COMTNBLOCKLISTENTRY (
    BLOCK_ID, TARGET, BLOCK_TYPE, REASON, REASON_EN, STATUS, EXPIRES_AT,
    OWNER, OWNER_EN, SOURCE, SOURCE_TITLE, SOURCE_FINGERPRINT, SOURCE_SEVERITY,
    REGISTERED_AT, ACTIVATED_AT, ACTIVATED_BY, REVIEWED_AT, REVIEWED_BY,
    LAST_ACTION_AT, LAST_ACTION_BY, USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'BL-MON-SEED-001', '198.51.100.42', 'IP', '관리자 로그인 버스트', 'Admin login burst', 'ACTIVE',
    TO_DATETIME('2026-03-28 23:59', 'YYYY-MM-DD HH24:MI'),
    'system', 'system', 'monitoring', 'Admin Login Burst', 'seed-fp-001', 'HIGH',
    TO_DATETIME('2026-03-28 09:10:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATETIME('2026-03-28 09:12:00', 'YYYY-MM-DD HH24:MI:SS'),
    'system', TO_DATETIME('2026-03-28 09:12:00', 'YYYY-MM-DD HH24:MI:SS'), 'system',
    TO_DATETIME('2026-03-28 09:12:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', 'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNBLOCKLISTENTRY (
    BLOCK_ID, TARGET, BLOCK_TYPE, REASON, REASON_EN, STATUS, EXPIRES_AT,
    OWNER, OWNER_EN, SOURCE, SOURCE_TITLE, SOURCE_FINGERPRINT, SOURCE_SEVERITY,
    REGISTERED_AT, ACTIVATED_AT, ACTIVATED_BY, REVIEWED_AT, REVIEWED_BY,
    LAST_ACTION_AT, LAST_ACTION_BY, USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'BL-MON-SEED-002', 'bot-agent/7.2', 'UA', '검색 스크래핑', 'Search scraping', 'REVIEW',
    NULL,
    'system', 'system', 'monitoring', 'Crawler Burst', 'seed-fp-002', 'MEDIUM',
    TO_DATETIME('2026-03-28 10:05:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, NULL, NULL, NULL,
    TO_DATETIME('2026-03-28 10:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'system', 'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNBLOCKLISTACTIONHIST (
    ACTION_ID, BLOCK_ID, TARGET, ACTION_TYPE, STATUS, DETAIL, DETAIL_EN,
    ACTOR_ID, ACTOR_NAME, SOURCE, ACTION_AT, EXPIRES_AT, USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'BL-MON-SEED-001-REGISTER-20260328091000', 'BL-MON-SEED-001', '198.51.100.42', 'REGISTER', 'REVIEW',
    '모니터링 차단 후보 등록', 'Monitoring block candidate registered',
    'system', 'system', 'monitoring', TO_DATETIME('2026-03-28 09:10:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATETIME('2026-03-28 23:59', 'YYYY-MM-DD HH24:MI'), 'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNBLOCKLISTACTIONHIST (
    ACTION_ID, BLOCK_ID, TARGET, ACTION_TYPE, STATUS, DETAIL, DETAIL_EN,
    ACTOR_ID, ACTOR_NAME, SOURCE, ACTION_AT, EXPIRES_AT, USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'BL-MON-SEED-001-ACTIVATE-20260328091200', 'BL-MON-SEED-001', '198.51.100.42', 'ACTIVATE', 'ACTIVE',
    '관리자 로그인 버스트', 'Admin login burst',
    'system', 'system', 'monitoring', TO_DATETIME('2026-03-28 09:12:00', 'YYYY-MM-DD HH24:MI:SS'),
    TO_DATETIME('2026-03-28 23:59', 'YYYY-MM-DD HH24:MI'), 'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNBLOCKLISTACTIONHIST (
    ACTION_ID, BLOCK_ID, TARGET, ACTION_TYPE, STATUS, DETAIL, DETAIL_EN,
    ACTOR_ID, ACTOR_NAME, SOURCE, ACTION_AT, EXPIRES_AT, USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'BL-MON-SEED-002-REGISTER-20260328100500', 'BL-MON-SEED-002', 'bot-agent/7.2', 'REGISTER', 'REVIEW',
    '모니터링 차단 후보 등록', 'Monitoring block candidate registered',
    'system', 'system', 'monitoring', TO_DATETIME('2026-03-28 10:05:00', 'YYYY-MM-DD HH24:MI:SS'),
    NULL, 'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);
