ALTER TABLE COMTNENTRPRSMBER
    ADD COLUMN PROJECT_ID VARCHAR(64);

ALTER TABLE COMTNINSTTINFO
    ADD COLUMN PROJECT_ID VARCHAR(64);

UPDATE COMTNENTRPRSMBER
SET PROJECT_ID = 'carbonet'
WHERE PROJECT_ID IS NULL;

UPDATE COMTNINSTTINFO
SET PROJECT_ID = 'carbonet'
WHERE PROJECT_ID IS NULL;

ALTER TABLE COMTNENTRPRSMBER
    ALTER COLUMN PROJECT_ID SET NOT NULL;

ALTER TABLE COMTNINSTTINFO
    ALTER COLUMN PROJECT_ID SET NOT NULL;

CREATE INDEX IDX_COMTNENTRPRSMBER_PROJECT_ID
    ON COMTNENTRPRSMBER (PROJECT_ID);

CREATE INDEX IDX_COMTNENTRPRSMBER_PROJECT_INSTT
    ON COMTNENTRPRSMBER (PROJECT_ID, INSTT_ID);

CREATE INDEX IDX_COMTNINSTTINFO_PROJECT_ID
    ON COMTNINSTTINFO (PROJECT_ID);

CREATE INDEX IDX_COMTNINSTTINFO_PROJECT_INSTT
    ON COMTNINSTTINFO (PROJECT_ID, INSTT_ID);
