-- CUBRID-safe external maintenance menu registration
-- Parent top: A005 (External Integration)
-- Parent group: A00501 (연계)
-- New page: A0050107 (점검 관리)

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0050107', '점검 관리', 'Maintenance', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'AMENU1' AND CODE = 'A0050107'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050107', '점검 관리', 'Maintenance', '/admin/external/maintenance', 'build', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE = 'A0050107'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '점검 관리',
    MENU_NM_EN = 'Maintenance',
    MENU_URL = '/admin/external/maintenance',
    MENU_ICON = 'build',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050107';

INSERT INTO COMTNMENUORDER (
    MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050107', 7, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE = 'A0050107'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 7,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050107';

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050107', 'ADMIN_A0050107_VIEW', '점검 관리', 'View Maintenance', '점검 관리 화면 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'ADMIN_A0050107_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0050107',
    FEATURE_NM = '점검 관리',
    FEATURE_NM_EN = 'View Maintenance',
    FEATURE_DC = '점검 관리 화면 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'ADMIN_A0050107_VIEW';

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT
)
SELECT src.AUTHOR_CODE, 'ADMIN_A0050107_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'ADMIN_A0050104_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'ADMIN_A0050107_VIEW'
  );
