-- CUBRID-safe project version management menu registration
-- Parent tree: A006 (시스템) > A00604 (백업)
-- New page: A0060404 (버전 관리)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00604', 'A0060404')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00604', 'A0060404')
   OR MENU_URL = '/admin/system/version'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0060404_VIEW',
    'A0060404_ANALYZE',
    'A0060404_APPLY',
    'A0060404_ROLLBACK'
)
ORDER BY FEATURE_CODE;

-- Detail code
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A00604', '백업', 'Backup', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A00604'
);

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0060404', '버전 관리', 'Version Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0060404'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = '버전 관리',
    CODE_DC = 'Version Management',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0060404';

-- Menu info
INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A00604', '백업', 'Backup', '#', 'backup', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A00604'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', '버전 관리', 'Version Management', '/admin/system/version', 'deployed_code', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0060404'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '버전 관리',
    MENU_NM_EN = 'Version Management',
    MENU_URL = '/admin/system/version',
    MENU_ICON = 'deployed_code',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060404';

-- Menu order
INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', 4, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0060404'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 4,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060404';

-- Features
INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', 'A0060404_VIEW', '버전 관리 조회', 'View Version Management', '버전 관리 콘솔 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060404_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', 'A0060404_ANALYZE', '업그레이드 영향 분석', 'Analyze Upgrade Impact', '버전 업그레이드 영향 분석 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060404_ANALYZE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', 'A0060404_APPLY', '업그레이드 적용', 'Apply Upgrade', '버전 업그레이드 적용 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060404_APPLY'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060404', 'A0060404_ROLLBACK', '롤백 실행', 'Run Rollback', '버전 롤백 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060404_ROLLBACK'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060404',
    FEATURE_NM = '버전 관리 조회',
    FEATURE_NM_EN = 'View Version Management',
    FEATURE_DC = '버전 관리 콘솔 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060404_VIEW';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060404',
    FEATURE_NM = '업그레이드 영향 분석',
    FEATURE_NM_EN = 'Analyze Upgrade Impact',
    FEATURE_DC = '버전 업그레이드 영향 분석 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060404_ANALYZE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060404',
    FEATURE_NM = '업그레이드 적용',
    FEATURE_NM_EN = 'Apply Upgrade',
    FEATURE_DC = '버전 업그레이드 적용 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060404_APPLY';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060404',
    FEATURE_NM = '롤백 실행',
    FEATURE_NM_EN = 'Run Rollback',
    FEATURE_DC = '버전 롤백 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060404_ROLLBACK';

-- Copy baseline role relations from other backup/restore pages when available.
INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'A0060404_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM (
    SELECT DISTINCT rel.AUTHOR_CODE, rel.GRANT_AUTHORITY_YN
    FROM COMTNAUTHORFUNCTIONRELATE rel
    JOIN COMTNMENUFUNCTIONINFO f
      ON f.FEATURE_CODE = rel.FEATURE_CODE
    JOIN COMTNMENUINFO m
      ON m.MENU_CODE = f.MENU_CODE
    WHERE COALESCE(m.MENU_URL, '') LIKE '/admin/system/backup%'
       OR COALESCE(m.MENU_URL, '') LIKE '/admin/system/restore%'
) src
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNAUTHORFUNCTIONRELATE x
    WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
      AND x.FEATURE_CODE = 'A0060404_VIEW'
);

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT 'ROLE_ADMIN', 'A0060404_VIEW', 'Y', CURRENT_DATETIME FROM db_root
WHERE EXISTS (
    SELECT 1
    FROM COMTNAUTHORINFO
    WHERE AUTHOR_CODE = 'ROLE_ADMIN'
)
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE
      WHERE AUTHOR_CODE = 'ROLE_ADMIN'
        AND FEATURE_CODE = 'A0060404_VIEW'
  );

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00604', 'A0060404')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00604', 'A0060404')
ORDER BY MENU_CODE;

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE IN ('A0060404');

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0060404_VIEW',
    'A0060404_ANALYZE',
    'A0060404_APPLY',
    'A0060404_ROLLBACK'
)
ORDER BY FEATURE_CODE;
