-- Provision /admin/emission/gwp-values as A0020109 under A002 > A00201

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0020109', 'GWP 값 관리', 'GWP Value Management', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'AMENU1' AND CODE = 'A0020109'
);

INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020109', 'GWP 값 관리', 'GWP Value Management', '/admin/emission/gwp-values', 'table_chart', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE = 'A0020109'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020109', 'A0020109_VIEW', 'GWP 값 조회', 'View GWP values', 'Open the GWP value management catalog', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020109_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020109', 'A0020109_EDIT', 'GWP 값 수정', 'Edit GWP values', 'Update seeded GWP values and notes', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020109_EDIT'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020109', 'A0020109_CREATE', 'GWP 값 등록', 'Create GWP values', 'Add new GWP rows', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020109_CREATE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020109', 'A0020109_DELETE', 'GWP 값 삭제', 'Delete GWP values', 'Delete GWP rows from the working catalog', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020109_DELETE'
);
