-- Version and Deploy Governance schema
-- Generated on 2026-04-17
-- Target DB: CUBRID-compatible SQL draft
-- Scope: COMMON_DB control-plane records for version control

CREATE TABLE RSN_RELEASE_UNIT (
    RELEASE_UNIT_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    RELEASE_VERSION VARCHAR(60) NOT NULL,
    RELEASE_STATUS VARCHAR(30) NOT NULL, -- DRAFT, PUBLISHED, DEPLOYED, ARCHIVED
    DESCRIPTION VARCHAR(2000),
    ROW_VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_BY VARCHAR(60) NOT NULL,
    UPDATED_BY VARCHAR(60) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (RELEASE_UNIT_ID)
);

CREATE INDEX IDX_RRU_PROJECT_STATUS ON RSN_RELEASE_UNIT (PROJECT_ID, RELEASE_STATUS);
CREATE INDEX IDX_RRU_VERSION ON RSN_RELEASE_UNIT (PROJECT_ID, RELEASE_VERSION);

CREATE TABLE RSN_RUNTIME_PACKAGE (
    RUNTIME_PACKAGE_ID VARCHAR(80) NOT NULL,
    RELEASE_UNIT_ID VARCHAR(80) NOT NULL,
    PACKAGE_TYPE VARCHAR(20) NOT NULL, -- JAR, WAR, DOCKER
    PACKAGE_HASH VARCHAR(100),
    ARTIFACT_PATH VARCHAR(500),
    FILE_SIZE BIGINT DEFAULT 0,
    BUILD_RUN_ID VARCHAR(80),
    ROW_VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_BY VARCHAR(60) NOT NULL,
    UPDATED_BY VARCHAR(60) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (RUNTIME_PACKAGE_ID)
);

CREATE INDEX IDX_RRP_RELEASE_UNIT ON RSN_RUNTIME_PACKAGE (RELEASE_UNIT_ID);
CREATE INDEX IDX_RRP_BUILD_RUN ON RSN_RUNTIME_PACKAGE (BUILD_RUN_ID);

CREATE TABLE RSN_DEPLOY_TRACE (
    DEPLOY_TRACE_ID VARCHAR(80) NOT NULL,
    RUNTIME_PACKAGE_ID VARCHAR(80) NOT NULL,
    TARGET_ENV VARCHAR(30) NOT NULL, -- LOCAL, DEV, STAGING, PROD
    DEPLOY_STATUS VARCHAR(30) NOT NULL, -- START, SUCCESS, FAILURE, ROLLBACK
    OPERATOR_ID VARCHAR(60) NOT NULL,
    DEPLOY_LOG CLOB,
    STARTED_AT DATETIME NOT NULL,
    FINISHED_AT DATETIME,
    ROW_VERSION INTEGER DEFAULT 0 NOT NULL,
    CREATED_BY VARCHAR(60) NOT NULL,
    UPDATED_BY VARCHAR(60) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (DEPLOY_TRACE_ID)
);

CREATE INDEX IDX_RDT_PACKAGE_ENV ON RSN_DEPLOY_TRACE (RUNTIME_PACKAGE_ID, TARGET_ENV);
CREATE INDEX IDX_RDT_STATUS ON RSN_DEPLOY_TRACE (TARGET_ENV, DEPLOY_STATUS);

-- Rollback order:
-- 1. DROP INDEX IDX_RDT_STATUS;
-- 2. DROP INDEX IDX_RDT_PACKAGE_ENV;
-- 3. DROP INDEX IDX_RRP_BUILD_RUN;
-- 4. DROP INDEX IDX_RRP_RELEASE_UNIT;
-- 5. DROP INDEX IDX_RRU_VERSION;
-- 6. DROP INDEX IDX_RRU_PROJECT_STATUS;
-- 7. DROP TABLE RSN_DEPLOY_TRACE;
-- 8. DROP TABLE RSN_RUNTIME_PACKAGE;
-- 9. DROP TABLE RSN_RELEASE_UNIT;
