-- CUBRID-safe external usage menu registration
-- Parent top: A005 (External Integration)
-- Parent group: A00501 (연계)
-- New page: A0050108 (API 사용량)

SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00501', 'A0050108')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00501', 'A0050108')
   OR MENU_URL = '/admin/external/usage'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'ADMIN_A0050108_VIEW';

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A00501', '연계', 'Integration', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A00501'
);

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0050108', 'API 사용량', 'API Usage', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0050108'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A00501', '연계', 'Integration', '#', 'hub', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A00501'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050108', 'API 사용량', 'API Usage', '/admin/external/usage', 'bar_chart', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0050108'
);

UPDATE COMTNMENUINFO
SET MENU_NM = 'API 사용량',
    MENU_NM_EN = 'API Usage',
    MENU_URL = '/admin/external/usage',
    MENU_ICON = 'bar_chart',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050108';

INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050108', 8, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0050108'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 8,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050108';

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050108', 'ADMIN_A0050108_VIEW', 'API 사용량', 'View API Usage', 'API 사용량 화면 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'ADMIN_A0050108_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0050108',
    FEATURE_NM = 'API 사용량',
    FEATURE_NM_EN = 'View API Usage',
    FEATURE_DC = 'API 사용량 화면 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'ADMIN_A0050108_VIEW';

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'ADMIN_A0050108_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'ADMIN_A0050104_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'ADMIN_A0050108_VIEW'
  );
