-- Persistent observability event tables
-- Generated on 2026-03-22
-- Apply after existing AUDIT_EVENT / TRACE_EVENT schema

CREATE TABLE ACCESS_EVENT (
    EVENT_ID VARCHAR(40) NOT NULL,
    TRACE_ID VARCHAR(40),
    REQUEST_ID VARCHAR(40),
    PAGE_ID VARCHAR(100),
    API_ID VARCHAR(200),
    REQUEST_URI VARCHAR(500) NOT NULL,
    HTTP_METHOD VARCHAR(16) NOT NULL,
    FEATURE_TYPE VARCHAR(40),
    ACTOR_ID VARCHAR(60),
    ACTOR_TYPE VARCHAR(30),
    ACTOR_ROLE VARCHAR(60),
    ACTOR_INSTT_ID VARCHAR(60),
    COMPANY_CONTEXT_ID VARCHAR(60),
    TARGET_COMPANY_CONTEXT_ID VARCHAR(60),
    REMOTE_ADDR VARCHAR(64),
    RESPONSE_STATUS INTEGER,
    DURATION_MS INTEGER,
    REQUEST_CONTENT_TYPE VARCHAR(120),
    QUERY_STRING VARCHAR(2000),
    PARAMETER_SUMMARY CLOB,
    ERROR_MESSAGE VARCHAR(2000),
    COMPANY_SCOPE_DECISION VARCHAR(120),
    COMPANY_SCOPE_REASON VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_ACCESS_EVENT_TRACE_ID ON ACCESS_EVENT (TRACE_ID);
CREATE INDEX IDX_ACCESS_EVENT_PAGE_ID ON ACCESS_EVENT (PAGE_ID);
CREATE INDEX IDX_ACCESS_EVENT_API_ID ON ACCESS_EVENT (API_ID);
CREATE INDEX IDX_ACCESS_EVENT_ACTOR_ID ON ACCESS_EVENT (ACTOR_ID);
CREATE INDEX IDX_ACCESS_EVENT_ACTOR_INSTT_ID ON ACCESS_EVENT (ACTOR_INSTT_ID);
CREATE INDEX IDX_ACCESS_EVENT_CREATED_AT ON ACCESS_EVENT (CREATED_AT);

CREATE TABLE ERROR_EVENT (
    ERROR_ID VARCHAR(40) NOT NULL,
    TRACE_ID VARCHAR(40),
    REQUEST_ID VARCHAR(40),
    PAGE_ID VARCHAR(100),
    API_ID VARCHAR(200),
    SOURCE_TYPE VARCHAR(40) NOT NULL,
    ERROR_TYPE VARCHAR(80) NOT NULL,
    ACTOR_ID VARCHAR(60),
    ACTOR_ROLE VARCHAR(60),
    ACTOR_INSTT_ID VARCHAR(60),
    REQUEST_URI VARCHAR(500),
    REMOTE_ADDR VARCHAR(64),
    MESSAGE VARCHAR(4000),
    STACK_SUMMARY CLOB,
    RESULT_STATUS VARCHAR(30),
    USER_AGENT VARCHAR(500),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ERROR_ID)
);

CREATE INDEX IDX_ERROR_EVENT_TRACE_ID ON ERROR_EVENT (TRACE_ID);
CREATE INDEX IDX_ERROR_EVENT_PAGE_ID ON ERROR_EVENT (PAGE_ID);
CREATE INDEX IDX_ERROR_EVENT_API_ID ON ERROR_EVENT (API_ID);
CREATE INDEX IDX_ERROR_EVENT_ACTOR_ID ON ERROR_EVENT (ACTOR_ID);
CREATE INDEX IDX_ERROR_EVENT_ACTOR_INSTT_ID ON ERROR_EVENT (ACTOR_INSTT_ID);
CREATE INDEX IDX_ERROR_EVENT_SOURCE_TYPE ON ERROR_EVENT (SOURCE_TYPE);
CREATE INDEX IDX_ERROR_EVENT_CREATED_AT ON ERROR_EVENT (CREATED_AT);
