-- CUBRID-safe platform studio menu registration
-- Parent group: A00601 (same as full-stack management)

-- Pre-check
SELECT MENU_CODE, MENU_URL, MENU_NM
FROM COMTNMENUINFO
WHERE MENU_CODE BETWEEN 'A0060109' AND 'A0060117'
   OR MENU_URL IN (
       '/admin/system/platform-studio',
       '/admin/system/screen-elements-management',
       '/admin/system/event-management-console',
       '/admin/system/function-management-console',
       '/admin/system/api-management-console',
       '/admin/system/controller-management-console',
       '/admin/system/db-table-management',
       '/admin/system/column-management-console',
       '/admin/system/automation-studio'
   )
ORDER BY MENU_CODE;

-- Detail codes
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060109', '플랫폼 스튜디오', 'Platform Studio', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060109');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060110', '화면 요소 관리', 'Screen Elements Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060110');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060111', '이벤트 관리', 'Event Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060111');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060112', '함수 콘솔', 'Function Console', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060112');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060113', 'API 관리', 'API Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060113');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060114', '컨트롤러 관리', 'Controller Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060114');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060115', 'DB 테이블 관리', 'DB Table Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060115');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060116', '컬럼 관리', 'Column Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060116');
INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0060117', '자동화 스튜디오', 'Automation Studio', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID='AMENU1' AND CODE='A0060117');

-- Menu info
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060109', '플랫폼 스튜디오', 'Platform Studio', '/admin/system/platform-studio', 'dashboard_customize', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060109');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060110', '화면 요소 관리', 'Screen Elements Management', '/admin/system/screen-elements-management', 'crop_landscape', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060110');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060111', '이벤트 관리', 'Event Management', '/admin/system/event-management-console', 'bolt', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060111');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060112', '함수 콘솔', 'Function Console', '/admin/system/function-management-console', 'functions', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060112');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060113', 'API 관리', 'API Management', '/admin/system/api-management-console', 'api', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060113');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060114', '컨트롤러 관리', 'Controller Management', '/admin/system/controller-management-console', 'account_tree', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060114');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060115', 'DB 테이블 관리', 'DB Table Management', '/admin/system/db-table-management', 'database', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060115');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060116', '컬럼 관리', 'Column Management', '/admin/system/column-management-console', 'view_column', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060116');
INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060117', '자동화 스튜디오', 'Automation Studio', '/admin/system/automation-studio', 'smart_toy', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE='A0060117');

-- Menu order
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060109', 9, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060109');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060110', 10, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060110');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060111', 11, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060111');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060112', 12, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060112');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060113', 13, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060113');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060114', 14, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060114');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060115', 15, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060115');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060116', 16, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060116');
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060117', 17, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE='A0060117');

-- View features
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060109', 'A0060109_VIEW', '플랫폼 스튜디오 조회', 'Platform Studio View', '플랫폼 스튜디오 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060109_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060110', 'A0060110_VIEW', '화면 요소 관리 조회', 'Screen Elements View', '화면 요소 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060110_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060111', 'A0060111_VIEW', '이벤트 관리 조회', 'Event Management View', '이벤트 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060111_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060112', 'A0060112_VIEW', '함수 콘솔 조회', 'Function Console View', '함수 콘솔 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060112_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060113', 'A0060113_VIEW', 'API 관리 조회', 'API Management View', 'API 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060113_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060114', 'A0060114_VIEW', '컨트롤러 관리 조회', 'Controller Management View', '컨트롤러 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060114_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060115', 'A0060115_VIEW', 'DB 테이블 관리 조회', 'DB Table Management View', 'DB 테이블 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060115_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060116', 'A0060116_VIEW', '컬럼 관리 조회', 'Column Management View', '컬럼 관리 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060116_VIEW');
INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0060117', 'A0060117_VIEW', '자동화 스튜디오 조회', 'Automation Studio View', '자동화 스튜디오 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE='A0060117_VIEW');

-- Author relations copied from full-stack management roles
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060109_VIEW', 'N', CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060109_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060110_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060110_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060111_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060111_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060112_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060112_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060113_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060113_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060114_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060114_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060115_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060115_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060116_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060116_VIEW');
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, 'A0060117_VIEW', 'N', CURRENT_DATETIME FROM COMTNAUTHORFUNCTIONRELATE src WHERE src.FEATURE_CODE='A0060108_VIEW'
  AND NOT EXISTS (SELECT 1 FROM COMTNAUTHORFUNCTIONRELATE x WHERE x.AUTHOR_CODE = src.AUTHOR_CODE AND x.FEATURE_CODE='A0060117_VIEW');

-- Post-check
SELECT MENU_CODE, MENU_URL, MENU_NM
FROM COMTNMENUINFO
WHERE MENU_CODE BETWEEN 'A0060109' AND 'A0060117'
ORDER BY MENU_CODE;

SELECT FEATURE_CODE, MENU_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE BETWEEN 'A0060109_VIEW' AND 'A0060117_VIEW'
ORDER BY FEATURE_CODE;
