-- CUBRID-safe verification center menu registration
-- Parent tree: A006 (시스템) > A00601 (시스템 관리)
-- New page: A0060128 (운영 검증 센터)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00601', 'A0060128')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00601', 'A0060128')
   OR MENU_URL = '/admin/system/verification-center'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0060128_VIEW',
    'A0060128_EXECUTE',
    'A0060128_TRACE'
)
ORDER BY FEATURE_CODE;

-- Detail code
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0060128', '운영 검증 센터', 'Verification Center', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0060128'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = '운영 검증 센터',
    CODE_DC = 'Verification Center',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0060128';

-- Menu info
INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060128', '운영 검증 센터', 'Verification Center', '/admin/system/verification-center', 'fact_check', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0060128'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '운영 검증 센터',
    MENU_NM_EN = 'Verification Center',
    MENU_URL = '/admin/system/verification-center',
    MENU_ICON = 'fact_check',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060128';

-- Menu order
INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060128', 28, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0060128'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 28,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0060128';

-- Features
INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060128', 'A0060128_VIEW', '운영 검증 센터 조회', 'View Verification Center', '운영 검증 센터 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060128_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060128', 'A0060128_EXECUTE', '검증 실행', 'Execute Verification', 'baseline 및 smoke 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060128_EXECUTE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0060128', 'A0060128_TRACE', '검증 이력 조회', 'Trace Verification History', '검증 로그와 증적 추적 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0060128_TRACE'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060128',
    FEATURE_NM = '운영 검증 센터 조회',
    FEATURE_NM_EN = 'View Verification Center',
    FEATURE_DC = '운영 검증 센터 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060128_VIEW';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060128',
    FEATURE_NM = '검증 실행',
    FEATURE_NM_EN = 'Execute Verification',
    FEATURE_DC = 'baseline 및 smoke 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060128_EXECUTE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0060128',
    FEATURE_NM = '검증 이력 조회',
    FEATURE_NM_EN = 'Trace Verification History',
    FEATURE_DC = '검증 로그와 증적 추적 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0060128_TRACE';

-- Copy baseline role relations from current asset / runtime governance pages when available.
INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'A0060128_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM (
    SELECT DISTINCT rel.AUTHOR_CODE, rel.GRANT_AUTHORITY_YN
    FROM COMTNAUTHORFUNCTIONRELATE rel
    JOIN COMTNMENUFUNCTIONINFO f
      ON f.FEATURE_CODE = rel.FEATURE_CODE
    WHERE f.MENU_CODE IN ('A0060118', 'A0060123', 'A1900108')
) src
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNAUTHORFUNCTIONRELATE x
    WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
      AND x.FEATURE_CODE = 'A0060128_VIEW'
);

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0060128';

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON, USE_AT
FROM COMTNMENUINFO
WHERE MENU_CODE = 'A0060128';

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, USE_AT
FROM COMTNMENUFUNCTIONINFO
WHERE MENU_CODE = 'A0060128'
ORDER BY FEATURE_CODE;
