-- Carbonet System Asset Inventory & Governance Schema
-- Generated on 2026-04-15
-- Target DB: CUBRID-compatible

-- 1. 전역 자산 인벤토리 (All System Assets)
CREATE TABLE SYSTEM_ASSET_INVENTORY (
    ASSET_ID VARCHAR(120) NOT NULL,
    ASSET_TYPE VARCHAR(40) NOT NULL, -- PAGE, COMPONENT, API, FUNCTION, QUERY, TABLE, BATCH, CONFIG 등
    ASSET_NAME VARCHAR(200) NOT NULL,
    ASSET_VERSION VARCHAR(40) DEFAULT '1.0.0',
    SOURCE_PATH VARCHAR(500),         -- 소스 코드 파일 경로
    SOURCE_SYMBOL VARCHAR(200),       -- 클래스명, 메소드명, 상수명 등
    CONTENT_HASH VARCHAR(64),         -- 변동 감지용 해시 (SHA-256)
    OWNER_DOMAIN VARCHAR(30),         -- admin, home, platform, shared
    CRITICALITY VARCHAR(20) DEFAULT 'MEDIUM', -- LOW, MEDIUM, HIGH, CRITICAL
    HEALTH_STATUS VARCHAR(30) DEFAULT 'OK',   -- OK, DRIFTED, ORPHANED, ERROR, INCOMPLETE
    LAST_SCAN_AT DATETIME,            -- 마지막 전수 조사 일시
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ASSET_ID)
);

CREATE INDEX IDX_ASSET_TYPE ON SYSTEM_ASSET_INVENTORY (ASSET_TYPE);
CREATE INDEX IDX_ASSET_OWNER ON SYSTEM_ASSET_INVENTORY (OWNER_DOMAIN);
CREATE INDEX IDX_ASSET_HEALTH ON SYSTEM_ASSET_INVENTORY (HEALTH_STATUS);

-- 2. 자산 조립 및 의존성 맵 (Asset Composition & Dependency)
CREATE TABLE SYSTEM_ASSET_COMPOSITION (
    COMPOSITION_ID VARCHAR(40) NOT NULL,
    PARENT_ASSET_ID VARCHAR(120) NOT NULL,
    CHILD_ASSET_ID VARCHAR(120) NOT NULL,
    RELATION_TYPE VARCHAR(30) NOT NULL, -- CONTAINS (포함), CALLS (호출), READS (참조), WRITES (수정)
    MAPPING_NOTES VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (COMPOSITION_ID),
    CONSTRAINT FK_ASSET_COMP_PARENT FOREIGN KEY (PARENT_ASSET_ID) REFERENCES SYSTEM_ASSET_INVENTORY (ASSET_ID),
    CONSTRAINT FK_ASSET_COMP_CHILD FOREIGN KEY (CHILD_ASSET_ID) REFERENCES SYSTEM_ASSET_INVENTORY (ASSET_ID)
);

CREATE INDEX IDX_ASSET_COMP_PARENT ON SYSTEM_ASSET_COMPOSITION (PARENT_ASSET_ID);
CREATE INDEX IDX_ASSET_COMP_CHILD ON SYSTEM_ASSET_COMPOSITION (CHILD_ASSET_ID);

-- 3. 자산 변동 및 스캔 이력 (Asset Scan & Drift History)
CREATE TABLE SYSTEM_ASSET_SCAN_LOG (
    SCAN_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(120) NOT NULL,
    PREVIOUS_HASH VARCHAR(64),
    CURRENT_HASH VARCHAR(64),
    SCAN_RESULT VARCHAR(30) NOT NULL, -- UNCHANGED, CHANGED, NEW, MISSING
    SCAN_DETAILS CLOB,                -- 변경 내용 요약 등
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (SCAN_ID)
);

CREATE INDEX IDX_ASSET_SCAN_ID ON SYSTEM_ASSET_SCAN_LOG (ASSET_ID);
CREATE INDEX IDX_ASSET_SCAN_TIME ON SYSTEM_ASSET_SCAN_LOG (CREATED_AT);

-- 4. 자산 수명주기 관리 계획 (Asset Lifecycle Plan)
CREATE TABLE SYSTEM_ASSET_LIFECYCLE_PLAN (
    PLAN_ID VARCHAR(40) NOT NULL,
    ASSET_ID VARCHAR(120) NOT NULL,
    TARGET_STAGE VARCHAR(30) NOT NULL,  -- CREATE, PUBLISH, DEPRECATE, RETIRE, ROLLBACK
    PLAN_STATUS VARCHAR(20) NOT NULL,   -- DRAFT, REQUESTED, APPROVED, REJECTED, COMPLETED, CANCELLED
    REQUESTER_ID VARCHAR(50) NOT NULL,
    APPROVER_ID VARCHAR(50),
    TARGET_DATE DATETIME,
    REASON CLOB,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_LIFECYCLE_ASSET FOREIGN KEY (ASSET_ID) REFERENCES SYSTEM_ASSET_INVENTORY (ASSET_ID)
);

CREATE INDEX IDX_LIFECYCLE_ASSET ON SYSTEM_ASSET_LIFECYCLE_PLAN (ASSET_ID);
CREATE INDEX IDX_LIFECYCLE_STATUS ON SYSTEM_ASSET_LIFECYCLE_PLAN (PLAN_STATUS);

-- 5. 수명주기 검증 증적 (Lifecycle Verification Evidence)
CREATE TABLE SYSTEM_ASSET_LIFECYCLE_EVIDENCE (
    EVIDENCE_ID VARCHAR(40) NOT NULL,
    PLAN_ID VARCHAR(40) NOT NULL,
    CHECKPOINT_KEY VARCHAR(100) NOT NULL, -- BUILD_OK, TEST_PASSED, SECURITY_CLEARED 등
    EVIDENCE_TYPE VARCHAR(30) NOT NULL,   -- TEXT, LINK, FILE_HASH, BOOLEAN
    EVIDENCE_VALUE CLOB,
    VERIFIED_BY VARCHAR(50),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (EVIDENCE_ID),
    CONSTRAINT FK_EVIDENCE_PLAN FOREIGN KEY (PLAN_ID) REFERENCES SYSTEM_ASSET_LIFECYCLE_PLAN (PLAN_ID)
);

CREATE INDEX IDX_EVIDENCE_PLAN ON SYSTEM_ASSET_LIFECYCLE_EVIDENCE (PLAN_ID);

-- 6. 기존 UI_PAGE_MANIFEST 및 UI_COMPONENT_REGISTRY와의 연동 뷰 (Optional)
-- 기존 테이블의 데이터를 SYSTEM_ASSET_INVENTORY로 마이그레이션하거나 동기화하는 트리거/절차 필요
