-- CUBRID-safe full-stack governance registry table

CREATE TABLE FULL_STACK_GOVERNANCE_REGISTRY (
    MENU_CODE VARCHAR(8) NOT NULL,
    PAGE_ID VARCHAR(100) NOT NULL,
    MENU_URL VARCHAR(300),
    SUMMARY VARCHAR(2000),
    OWNER_SCOPE VARCHAR(60),
    NOTES VARCHAR(4000),
    FRONTEND_SOURCES_JSON CLOB,
    COMPONENT_IDS_JSON CLOB,
    EVENT_IDS_JSON CLOB,
    FUNCTION_IDS_JSON CLOB,
    PARAMETER_SPECS_JSON CLOB,
    RESULT_SPECS_JSON CLOB,
    API_IDS_JSON CLOB,
    SCHEMA_IDS_JSON CLOB,
    TABLE_NAMES_JSON CLOB,
    COLUMN_NAMES_JSON CLOB,
    FEATURE_CODES_JSON CLOB,
    COMMON_CODE_GROUPS_JSON CLOB,
    TAGS_JSON CLOB,
    CREATED_AT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    SOURCE_TYPE VARCHAR(30) DEFAULT 'MANUAL' NOT NULL,
    PRIMARY KEY (MENU_CODE)
);

CREATE INDEX IDX_FSGR_PAGE_ID ON FULL_STACK_GOVERNANCE_REGISTRY (PAGE_ID);
CREATE INDEX IDX_FSGR_UPDATED_AT ON FULL_STACK_GOVERNANCE_REGISTRY (UPDATED_AT);
