-- Enable emission variable management features for standard admin roles

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT role_map.AUTHOR_CODE, role_map.FEATURE_CODE, 'Y', CURRENT_DATETIME
FROM (
    SELECT 'ROLE_SYSTEM_MASTER' AS AUTHOR_CODE, 'A0020107_VIEW' AS FEATURE_CODE FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020107_SESSION_SAVE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020107_CALCULATE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020107_FACTOR_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020107_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020107_SESSION_SAVE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020107_CALCULATE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020107_FACTOR_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020107_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020107_SESSION_SAVE' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020107_CALCULATE' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020107_FACTOR_VIEW' FROM db_root
) role_map
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNAUTHORFUNCTIONRELATE x
    WHERE x.AUTHOR_CODE = role_map.AUTHOR_CODE
      AND x.FEATURE_CODE = role_map.FEATURE_CODE
);

UPDATE COMTNAUTHORFUNCTIONRELATE
SET GRANT_AUTHORITY_YN = 'Y'
WHERE AUTHOR_CODE IN ('ROLE_SYSTEM_MASTER', 'ROLE_SYSTEM_ADMIN', 'ROLE_ADMIN')
  AND FEATURE_CODE IN (
      'A0020107_VIEW',
      'A0020107_SESSION_SAVE',
      'A0020107_CALCULATE',
      'A0020107_FACTOR_VIEW'
  );

SELECT AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN
FROM COMTNAUTHORFUNCTIONRELATE
WHERE AUTHOR_CODE IN ('ROLE_SYSTEM_MASTER', 'ROLE_SYSTEM_ADMIN', 'ROLE_ADMIN')
  AND FEATURE_CODE IN (
      'A0020107_VIEW',
      'A0020107_SESSION_SAVE',
      'A0020107_CALCULATE',
      'A0020107_FACTOR_VIEW'
  )
ORDER BY AUTHOR_CODE, FEATURE_CODE;
