-- Add project ownership to observability event tables and support project-level queries.

ALTER TABLE AUDIT_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);
ALTER TABLE TRACE_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);
ALTER TABLE ACCESS_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);
ALTER TABLE ERROR_EVENT ADD COLUMN PROJECT_ID VARCHAR(80);

CREATE INDEX IDX_AUDIT_EVENT_PROJECT_ID ON AUDIT_EVENT (PROJECT_ID);
CREATE INDEX IDX_TRACE_EVENT_PROJECT_ID ON TRACE_EVENT (PROJECT_ID);
CREATE INDEX IDX_ACCESS_EVENT_PROJECT_ID ON ACCESS_EVENT (PROJECT_ID);
CREATE INDEX IDX_ERROR_EVENT_PROJECT_ID ON ERROR_EVENT (PROJECT_ID);

CREATE INDEX IDX_ACCESS_EVENT_PROJECT_INSTT ON ACCESS_EVENT (PROJECT_ID, ACTOR_INSTT_ID);
CREATE INDEX IDX_ERROR_EVENT_PROJECT_INSTT ON ERROR_EVENT (PROJECT_ID, ACTOR_INSTT_ID);
