-- IP whitelist persistence migration
-- Apply order:
-- 1. Run `20260328_ip_whitelist_persistence.sql` once if the tables do not exist yet.
-- 2. Run this migration to refresh initial seed rows safely.
--
-- Notes:
-- - This migration is designed to be re-runnable for the bundled seed IDs.
-- - Schema DDL is intentionally split out because CUBRID lacks convenient portable
--   `CREATE TABLE IF NOT EXISTS` handling across all deployment environments.

DELETE FROM COMTNIPWHITELISTRULE
WHERE RULE_ID IN ('WL-001', 'WL-002', 'WL-003', 'WL-004');

DELETE FROM COMTNIPWHITELISTREQUEST
WHERE REQUEST_ID IN ('REQ-240312-01', 'REQ-240311-07', 'REQ-240307-02');

INSERT INTO COMTNIPWHITELISTREQUEST (
    REQUEST_ID, RULE_ID, IP_ADDRESS, ACCESS_SCOPE, REASON, REASON_EN,
    APPROVAL_STATUS, APPROVAL_STATUS_EN, REQUESTED_AT, REQUESTER, REQUESTER_EN,
    REVIEW_NOTE, REVIEWED_AT, REVIEWED_BY, REVIEWED_BY_EN, EXPIRES_AT, MEMO, MEMO_EN,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'REQ-240312-01', 'WL-003', '175.213.44.82', 'ADMIN', '협력사 취약점 점검', 'Vendor security inspection',
    '검토중', 'Under Review', TO_DATETIME('2026-03-12 08:45', 'YYYY-MM-DD HH24:MI'), '보안담당 김민수', 'Security Officer Minsu Kim',
    '', NULL, '', '', TO_DATETIME('2026-03-20 18:00', 'YYYY-MM-DD HH24:MI'), '2026-03-20까지 임시 허용', 'Temporary access until 2026-03-20',
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTREQUEST (
    REQUEST_ID, RULE_ID, IP_ADDRESS, ACCESS_SCOPE, REASON, REASON_EN,
    APPROVAL_STATUS, APPROVAL_STATUS_EN, REQUESTED_AT, REQUESTER, REQUESTER_EN,
    REVIEW_NOTE, REVIEWED_AT, REVIEWED_BY, REVIEWED_BY_EN, EXPIRES_AT, MEMO, MEMO_EN,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'REQ-240311-07', NULL, '210.96.14.0/24', 'API', '관계기관 API 테스트', 'Partner API test',
    '승인완료', 'Approved', TO_DATETIME('2026-03-11 16:10', 'YYYY-MM-DD HH24:MI'), '플랫폼운영팀 이지훈', 'Platform Ops Jihun Lee',
    '', TO_DATETIME('2026-03-11 16:40', 'YYYY-MM-DD HH24:MI'), '이지훈', 'Jihun Lee', NULL, '', '',
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTREQUEST (
    REQUEST_ID, RULE_ID, IP_ADDRESS, ACCESS_SCOPE, REASON, REASON_EN,
    APPROVAL_STATUS, APPROVAL_STATUS_EN, REQUESTED_AT, REQUESTER, REQUESTER_EN,
    REVIEW_NOTE, REVIEWED_AT, REVIEWED_BY, REVIEWED_BY_EN, EXPIRES_AT, MEMO, MEMO_EN,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'REQ-240307-02', NULL, '121.166.77.19', 'ADMIN', '퇴사자 계정 사용 종료', 'User retired',
    '반려', 'Rejected', TO_DATETIME('2026-03-07 11:20', 'YYYY-MM-DD HH24:MI'), '감사담당 박선영', 'Audit Officer Sunyoung Park',
    '허용 사유 종료', TO_DATETIME('2026-03-07 11:45', 'YYYY-MM-DD HH24:MI'), '보안운영자', 'Security Operator', NULL, '', '',
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTRULE (
    RULE_ID, REQUEST_ID, IP_ADDRESS, ACCESS_SCOPE, DESCRIPTION, DESCRIPTION_EN,
    OWNER, OWNER_EN, STATUS, UPDATED_AT, MEMO, MEMO_EN, EXPIRES_AT,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'WL-001', NULL, '203.248.117.0/24', 'ADMIN', '운영센터 고정망', 'Primary office network',
    '정책관리팀', 'Policy Admin Team', 'ACTIVE', TO_DATETIME('2026-03-10 09:20', 'YYYY-MM-DD HH24:MI'),
    '상시 허용', 'Always allowed', NULL,
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTRULE (
    RULE_ID, REQUEST_ID, IP_ADDRESS, ACCESS_SCOPE, DESCRIPTION, DESCRIPTION_EN,
    OWNER, OWNER_EN, STATUS, UPDATED_AT, MEMO, MEMO_EN, EXPIRES_AT,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'WL-002', NULL, '10.10.20.15', 'BATCH', '배치 서버', 'Batch server',
    '플랫폼운영팀', 'Platform Ops Team', 'ACTIVE', TO_DATETIME('2026-03-09 18:40', 'YYYY-MM-DD HH24:MI'),
    'API 연동 전용', 'API integration only', NULL,
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTRULE (
    RULE_ID, REQUEST_ID, IP_ADDRESS, ACCESS_SCOPE, DESCRIPTION, DESCRIPTION_EN,
    OWNER, OWNER_EN, STATUS, UPDATED_AT, MEMO, MEMO_EN, EXPIRES_AT,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'WL-003', 'REQ-240312-01', '175.213.44.82', 'ADMIN', '외부 협력사 점검 단말', 'Vendor inspection terminal',
    '보안담당', 'Security Officer', 'PENDING', TO_DATETIME('2026-03-12 08:50', 'YYYY-MM-DD HH24:MI'),
    '2026-03-20까지 임시 허용', 'Temporary access until 2026-03-20', TO_DATETIME('2026-03-20 18:00', 'YYYY-MM-DD HH24:MI'),
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);

INSERT INTO COMTNIPWHITELISTRULE (
    RULE_ID, REQUEST_ID, IP_ADDRESS, ACCESS_SCOPE, DESCRIPTION, DESCRIPTION_EN,
    OWNER, OWNER_EN, STATUS, UPDATED_AT, MEMO, MEMO_EN, EXPIRES_AT,
    USE_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
) VALUES (
    'WL-004', NULL, '192.168.0.0/16', 'INTERNAL', '사내 VPN 대역', 'Internal VPN range',
    '인프라팀', 'Infrastructure Team', 'INACTIVE', TO_DATETIME('2026-02-25 14:05', 'YYYY-MM-DD HH24:MI'),
    'VPN 정책 재정비 대기', 'Waiting for VPN policy update', NULL,
    'Y', 'seed', CURRENT_DATETIME, 'seed', CURRENT_DATETIME
);
