-- Provision /admin/emission/validate as A0020104 under A002 > A00201

INSERT INTO COMTCCMMNDETAILCODE (CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'AMENU1', 'A0020104', '검증 관리', 'Verification Management', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'AMENU1' AND CODE = 'A0020104'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = '검증 관리',
    CODE_DC = 'Verification Management',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME,
    LAST_UPDUSR_ID = 'codex'
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0020104';

INSERT INTO COMTNMENUINFO (MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', '검증 관리', 'Verification Management', '/admin/emission/validate', 'verified', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE = 'A0020104'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '검증 관리',
    MENU_NM_EN = 'Verification Management',
    MENU_URL = '/admin/emission/validate',
    MENU_ICON = 'verified',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME,
    LAST_UPDUSR_ID = 'codex'
WHERE MENU_CODE = 'A0020104';

INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0020104', 4, CURRENT_DATETIME, CURRENT_DATETIME
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE = 'A0020104'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_VIEW', '검증 관리 조회', 'View Verification Management', 'Open the verification management queue', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_ASSIGN', '검증 담당자 배정', 'Assign Verifier', 'Assign verification owners and queue items', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_ASSIGN'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_REVIEW', '검증 검토', 'Review Verification', 'Review verification evidence and result deltas', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_REVIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_REJECT', '검증 반려', 'Reject Verification', 'Reject verification with supplement feedback', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_REJECT'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_APPROVE', '검증 승인', 'Approve Verification', 'Approve verified emission results', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_APPROVE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID)
SELECT 'A0020104', 'A0020104_TRACE', '검증 이력 추적', 'Trace Verification History', 'Trace verification actions and operator evidence', 'Y', CURRENT_DATETIME, 'codex'
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020104_TRACE'
);
