UPDATE COMTNMENUINFO
SET MENU_URL = '/admin/member/register',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0010102';

UPDATE COMTNMENUINFO
SET MENU_URL = '/admin/member/withdrawn',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0010106';

UPDATE COMTNMENUINFO
SET MENU_URL = '/admin/member/activate',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0010107';

SELECT MENU_CODE, MENU_URL
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A0010102', 'A0010106', 'A0010107')
ORDER BY MENU_CODE;
