-- Carbonet System Asset Inventory Expansion Patch
-- Generated on 2026-04-15
-- Adds ownership and family fields for enhanced asset governance

ALTER TABLE SYSTEM_ASSET_INVENTORY ADD COLUMN ASSET_FAMILY VARCHAR(30);
ALTER TABLE SYSTEM_ASSET_INVENTORY ADD COLUMN OWNER_SCOPE VARCHAR(30);
ALTER TABLE SYSTEM_ASSET_INVENTORY ADD COLUMN OPERATOR_OWNER VARCHAR(100);
ALTER TABLE SYSTEM_ASSET_INVENTORY ADD COLUMN SERVICE_OWNER VARCHAR(100);

-- Update existing data with default families based on asset type (heuristic)
UPDATE SYSTEM_ASSET_INVENTORY SET ASSET_FAMILY = 'SERVICE' WHERE ASSET_TYPE IN ('PAGE', 'COMPONENT', 'FUNCTION', 'API');
UPDATE SYSTEM_ASSET_INVENTORY SET ASSET_FAMILY = 'INFRA' WHERE ASSET_TYPE IN ('NODE', 'ENVIRONMENT', 'SCHEDULER', 'BATCH');
UPDATE SYSTEM_ASSET_INVENTORY SET ASSET_FAMILY = 'RECOVERY' WHERE ASSET_TYPE IN ('BACKUP', 'RESTORE');
UPDATE SYSTEM_ASSET_INVENTORY SET ASSET_FAMILY = 'INTEGRATION' WHERE ASSET_TYPE IN ('CONNECTION', 'WEBHOOK');
UPDATE SYSTEM_ASSET_INVENTORY SET ASSET_FAMILY = 'CONTENT' WHERE ASSET_TYPE IN ('FILE', 'TEMPLATE', 'POPUP');

CREATE INDEX IDX_ASSET_FAMILY ON SYSTEM_ASSET_INVENTORY (ASSET_FAMILY);
CREATE INDEX IDX_ASSET_SCOPE ON SYSTEM_ASSET_INVENTORY (OWNER_SCOPE);
