-- CUBRID-safe GWP value management table

CREATE TABLE ADMIN_EMISSION_GWP_VALUE (
    ROW_ID VARCHAR(20) NOT NULL,
    SECTION_CODE VARCHAR(40) NOT NULL,
    SECTION_ORDR INTEGER NOT NULL,
    COMMON_NAME VARCHAR(500) NOT NULL,
    FORMULA VARCHAR(250) NOT NULL,
    AR4_VALUE VARCHAR(60),
    AR5_VALUE VARCHAR(60),
    AR6_VALUE VARCHAR(60),
    NOTE_TXT VARCHAR(4000),
    SOURCE_DOCUMENT_NM VARCHAR(200) NOT NULL,
    SOURCE_PAGE_NO INTEGER,
    SORT_ORDR INTEGER NOT NULL,
    FRST_REGIST_PNTTM DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    FRST_REGISTER_ID VARCHAR(100),
    LAST_UPDT_PNTTM DATETIME DEFAULT CURRENT_DATETIME NOT NULL,
    LAST_UPDUSR_ID VARCHAR(100),
    PRIMARY KEY (ROW_ID)
);

CREATE INDEX IDX_ADMIN_EMISSION_GWP_VALUE_01
    ON ADMIN_EMISSION_GWP_VALUE (SECTION_CODE, SECTION_ORDR, SORT_ORDR);

CREATE INDEX IDX_ADMIN_EMISSION_GWP_VALUE_02
    ON ADMIN_EMISSION_GWP_VALUE (COMMON_NAME);
