-- Move /admin/emission/site-management from legacy A0080101 to A0020105
-- Target tree: A002 (배출/인증) > A00201 (배출) > A0020105 (배출지 관리)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A002', 'A00201', 'A0020105', 'A0080101')
ORDER BY CODE;

SELECT MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A0020105', 'A0080101')
   OR MENU_URL = '/admin/emission/site-management'
ORDER BY MENU_CODE;

SELECT FEATURE_CODE, MENU_CODE, FEATURE_NM, USE_AT
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE LIKE 'A0020105_%'
   OR FEATURE_CODE LIKE 'A0080101_%'
ORDER BY FEATURE_CODE;

-- Ensure target page detail code exists
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0020105', '배출지 관리', 'Emission Site Management', 'Y', CURRENT_DATETIME, 'codex'
FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0020105'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = '배출지 관리',
    CODE_DC = 'Emission Site Management',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME,
    LAST_UPDUSR_ID = 'codex'
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0020105';

-- Ensure target menu metadata exists
INSERT INTO COMTNMENUINFO (
    MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', '배출지 관리', 'Emission Site Management', '/admin/emission/site-management', 'factory', 'Y',
       CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0020105'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '배출지 관리',
    MENU_NM_EN = 'Emission Site Management',
    MENU_URL = '/admin/emission/site-management',
    MENU_ICON = 'factory',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0020105';

-- Place the page under the emission group in menu order
INSERT INTO COMTNMENUORDER (MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM)
SELECT 'A0020105', 5, CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0020105'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 5,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0020105';

-- Ensure new feature catalog exists
INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_VIEW', '배출지 관리 조회', 'View Emission Site Management',
       'Emission site management page access', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_REGISTER', '배출지 등록', 'Register Emission Site',
       'Create and register emission sites', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_REGISTER'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_DATA_INPUT', '배출 데이터 입력', 'Emission Data Input',
       'Input emission activity data', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_DATA_INPUT'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_CALCULATION', '산정 로직 등록', 'Calculation Logic Registration',
       'Manage emission calculation logic', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_CALCULATION'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_DOCUMENT', '서류 보완 관리', 'Document Supplement',
       'Manage document supplement workflows', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_DOCUMENT'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_HISTORY', '이력 확인', 'History Review',
       'Review emission site history', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_HISTORY'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_REPORT', '보고서 출력', 'Report Export',
       'Generate and export emission reports', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_REPORT'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_MANAGE', '배출지 운영 관리', 'Emission Site Administration',
       'Manage emission site administration', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_MANAGE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0020105', 'A0020105_MONITOR', '종합 배출 모니터링 리포트', 'Integrated Emission Monitoring Report',
       'View integrated emission monitoring reports', 'Y', CURRENT_DATETIME, CURRENT_DATETIME
FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'A0020105_MONITOR'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0020105',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE LIKE 'A0020105_%';

-- Copy legacy author grants to the new feature codes
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT src.AUTHOR_CODE, map.new_feature_code, src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
JOIN (
    SELECT 'A0080101_VIEW' AS legacy_feature_code, 'A0020105_VIEW' AS new_feature_code FROM db_root
    UNION ALL SELECT 'A0080101_REGISTER', 'A0020105_REGISTER' FROM db_root
    UNION ALL SELECT 'A0080101_DATA_INPUT', 'A0020105_DATA_INPUT' FROM db_root
    UNION ALL SELECT 'A0080101_CALCULATION', 'A0020105_CALCULATION' FROM db_root
    UNION ALL SELECT 'A0080101_DOCUMENT', 'A0020105_DOCUMENT' FROM db_root
    UNION ALL SELECT 'A0080101_HISTORY', 'A0020105_HISTORY' FROM db_root
    UNION ALL SELECT 'A0080101_REPORT', 'A0020105_REPORT' FROM db_root
    UNION ALL SELECT 'A0080101_MANAGE', 'A0020105_MANAGE' FROM db_root
    UNION ALL SELECT 'A0080101_MONITOR', 'A0020105_MONITOR' FROM db_root
) map ON map.legacy_feature_code = src.FEATURE_CODE
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNAUTHORFUNCTIONRELATE x
    WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
      AND x.FEATURE_CODE = map.new_feature_code
);

-- Fallback grants for standard admin roles when no legacy relation exists
INSERT INTO COMTNAUTHORFUNCTIONRELATE (AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT)
SELECT role_map.AUTHOR_CODE, role_map.FEATURE_CODE, 'N', CURRENT_DATETIME
FROM (
    SELECT 'ROLE_SYSTEM_MASTER' AS AUTHOR_CODE, 'A0020105_VIEW' AS FEATURE_CODE FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_REGISTER' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_DATA_INPUT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_CALCULATION' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_DOCUMENT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_HISTORY' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_REPORT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_MANAGE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_MASTER', 'A0020105_MONITOR' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_REGISTER' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_DATA_INPUT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_CALCULATION' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_DOCUMENT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_HISTORY' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_REPORT' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_MANAGE' FROM db_root
    UNION ALL SELECT 'ROLE_SYSTEM_ADMIN', 'A0020105_MONITOR' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_VIEW' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_REGISTER' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_DATA_INPUT' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_CALCULATION' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_DOCUMENT' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_HISTORY' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_REPORT' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_MANAGE' FROM db_root
    UNION ALL SELECT 'ROLE_ADMIN', 'A0020105_MONITOR' FROM db_root
) role_map
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNAUTHORFUNCTIONRELATE x
    WHERE x.AUTHOR_CODE = role_map.AUTHOR_CODE
      AND x.FEATURE_CODE = role_map.FEATURE_CODE
);

-- Retire legacy page menu so only the new A002 tree is exposed
UPDATE COMTCCMMNDETAILCODE
SET USE_AT = 'N',
    LAST_UPDT_PNTTM = CURRENT_DATETIME,
    LAST_UPDUSR_ID = 'codex'
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0080101';

UPDATE COMTNMENUINFO
SET USE_AT = 'N',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0080101';

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A0020105', 'A0080101')
ORDER BY CODE;

SELECT MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A0020105', 'A0080101')
ORDER BY MENU_CODE;

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE = 'A0020105';

SELECT FEATURE_CODE, MENU_CODE, FEATURE_NM, USE_AT
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE LIKE 'A0020105_%'
ORDER BY FEATURE_CODE;

SELECT AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE LIKE 'A0020105_%'
ORDER BY AUTHOR_CODE, FEATURE_CODE;
