-- CUBRID-safe external sync menu registration
-- Parent top: A005 (External Integration)
-- Parent group: A00501 (연계)
-- New page: A0050104 (동기화 실행)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00501', 'A0050104')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00501', 'A0050104')
   OR MENU_URL = '/admin/external/sync'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'ADMIN_A0050104_VIEW';

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE IN ('A00501', 'A0050104')
ORDER BY MENU_CODE;

-- Ensure parent group detail code exists
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A00501', '연계', 'Integration', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A00501'
);

-- Ensure page detail code exists
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0050104', '동기화 실행', 'Sync Execution', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0050104'
);

-- Ensure parent group menu info exists
INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A00501', '연계', 'Integration', '#', 'hub', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A00501'
);

-- Ensure page menu info exists
INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050104', '동기화 실행', 'Sync Execution', '/admin/external/sync', 'sync', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0050104'
);

-- Keep URL and names aligned even if the row already exists
UPDATE COMTNMENUINFO
SET MENU_NM = '동기화 실행',
    MENU_NM_EN = 'Sync Execution',
    MENU_URL = '/admin/external/sync',
    MENU_ICON = 'sync',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050104';

-- Menu order
INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050104', 4, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0050104'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 4,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050104';

-- Default VIEW feature
INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0050104', 'ADMIN_A0050104_VIEW', '동기화 실행', 'View Run Synchronization', '동기화 실행 화면 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'ADMIN_A0050104_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0050104',
    FEATURE_NM = '동기화 실행',
    FEATURE_NM_EN = 'View Run Synchronization',
    FEATURE_DC = '동기화 실행 화면 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'ADMIN_A0050104_VIEW';

-- Copy default author relations from the existing external connection list view
INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'ADMIN_A0050104_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'ADMIN_A0050101_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'ADMIN_A0050104_VIEW'
  );

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A00501', 'A0050104')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A00501', 'A0050104')
ORDER BY MENU_CODE;

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE IN ('A0050104')
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'ADMIN_A0050104_VIEW';

SELECT AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE = 'ADMIN_A0050104_VIEW'
ORDER BY AUTHOR_CODE;
