-- CUBRID-safe external retry menu registration
-- Parent top: A005 (External Integration)
-- Parent group: A00501 (연계)
-- New page: A0050105 (재시도 관리)

INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0050105', '재시도 관리', 'Retry Control', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTCCMMNDETAILCODE WHERE CODE_ID = 'AMENU1' AND CODE = 'A0050105'
);

INSERT INTO COMTNMENUINFO (
    MENU_CODE, MENU_NM, MENU_NM_EN, MENU_URL, MENU_ICON, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050105', '재시도 관리', 'Retry Control', '/admin/external/retry', 'replay', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUINFO WHERE MENU_CODE = 'A0050105'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '재시도 관리',
    MENU_NM_EN = 'Retry Control',
    MENU_URL = '/admin/external/retry',
    MENU_ICON = 'replay',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050105';

INSERT INTO COMTNMENUORDER (
    MENU_CODE, SORT_ORDR, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050105', 5, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUORDER WHERE MENU_CODE = 'A0050105'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 5,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0050105';

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN, FEATURE_DC, USE_AT, FRST_REGIST_PNTTM, LAST_UPDT_PNTTM
)
SELECT 'A0050105', 'ADMIN_A0050105_VIEW', '재시도 관리', 'View Retry Control', '재시도 관리 화면 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1 FROM COMTNMENUFUNCTIONINFO WHERE FEATURE_CODE = 'ADMIN_A0050105_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0050105',
    FEATURE_NM = '재시도 관리',
    FEATURE_NM_EN = 'View Retry Control',
    FEATURE_DC = '재시도 관리 화면 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'ADMIN_A0050105_VIEW';

INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN, CREAT_DT
)
SELECT src.AUTHOR_CODE, 'ADMIN_A0050105_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'ADMIN_A0050104_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'ADMIN_A0050105_VIEW'
  );
