-- Admin save tracking and deployable DB patch queue
-- Generated on 2026-04-14

CREATE TABLE DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID                VARCHAR(80) PRIMARY KEY,
    TABLE_NAME               VARCHAR(160) NOT NULL,
    POLICY_CODE              VARCHAR(40) NOT NULL,
    CHANGE_TYPES_JSON        VARCHAR(1000),
    MASKING_PROFILE_CODE     VARCHAR(40),
    SQL_RENDER_MODE          VARCHAR(40),
    ACTIVE_YN                CHAR(1) DEFAULT 'Y' NOT NULL,
    POLICY_REASON            VARCHAR(1000),
    CREATED_AT               DATETIME NOT NULL,
    UPDATED_AT               DATETIME NOT NULL,
    CREATED_BY               VARCHAR(80),
    UPDATED_BY               VARCHAR(80)
);

CREATE UNIQUE INDEX UX_DB_CHANGE_PROMOTION_POLICY_TABLE
    ON DB_CHANGE_PROMOTION_POLICY (TABLE_NAME);

CREATE TABLE BUSINESS_CHANGE_LOG (
    CHANGE_LOG_ID            VARCHAR(120) PRIMARY KEY,
    TRACE_ID                 VARCHAR(40),
    REQUEST_ID               VARCHAR(40),
    PROJECT_ID               VARCHAR(80),
    MENU_CODE                VARCHAR(30),
    PAGE_ID                  VARCHAR(100),
    API_PATH                 VARCHAR(300),
    HTTP_METHOD              VARCHAR(20),
    ACTOR_ID                 VARCHAR(80),
    ACTOR_ROLE               VARCHAR(80),
    ACTOR_SCOPE_ID           VARCHAR(80),
    TARGET_TABLE_NAME        VARCHAR(160) NOT NULL,
    TARGET_PK_JSON           CLOB,
    ENTITY_TYPE              VARCHAR(80),
    ENTITY_ID                VARCHAR(120),
    CHANGE_TYPE              VARCHAR(20) NOT NULL,
    BEFORE_SUMMARY_JSON      CLOB,
    AFTER_SUMMARY_JSON       CLOB,
    CHANGE_SUMMARY           VARCHAR(1000),
    PROMOTION_POLICY_CODE    VARCHAR(40) NOT NULL,
    QUEUE_DECISION_CODE      VARCHAR(40) NOT NULL,
    QUEUE_REQUESTED_YN       CHAR(1) DEFAULT 'N' NOT NULL,
    QUEUE_ID                 VARCHAR(120),
    APPROVAL_REQUIRED_YN     CHAR(1) DEFAULT 'N' NOT NULL,
    APPROVAL_STATUS          VARCHAR(40),
    CAPTURED_AT              DATETIME NOT NULL,
    CREATED_AT               DATETIME NOT NULL
);

CREATE INDEX IX_BUSINESS_CHANGE_LOG_CAPTURED_AT
    ON BUSINESS_CHANGE_LOG (CAPTURED_AT);

CREATE INDEX IX_BUSINESS_CHANGE_LOG_TARGET
    ON BUSINESS_CHANGE_LOG (TARGET_TABLE_NAME, CHANGE_TYPE, CAPTURED_AT);

CREATE INDEX IX_BUSINESS_CHANGE_LOG_ACTOR
    ON BUSINESS_CHANGE_LOG (ACTOR_ID, CAPTURED_AT);

CREATE INDEX IX_BUSINESS_CHANGE_LOG_QUEUE
    ON BUSINESS_CHANGE_LOG (QUEUE_ID, QUEUE_REQUESTED_YN, CAPTURED_AT);

CREATE TABLE DEPLOYABLE_DB_PATCH_QUEUE (
    QUEUE_ID                 VARCHAR(120) PRIMARY KEY,
    PROJECT_ID               VARCHAR(80) NOT NULL,
    SOURCE_CHANGE_IDS_JSON   CLOB,
    TARGET_ENV               VARCHAR(40) NOT NULL,
    PATCH_FORMAT_CODE        VARCHAR(40) NOT NULL,
    PATCH_KIND_CODE          VARCHAR(40) NOT NULL,
    TARGET_TABLE_NAME        VARCHAR(160) NOT NULL,
    TARGET_KEYS_JSON         CLOB,
    PATCH_PAYLOAD_JSON       CLOB,
    RENDERED_SQL_PREVIEW     CLOB,
    CHECKSUM_SHA256          VARCHAR(128),
    RISK_LEVEL               VARCHAR(40) NOT NULL,
    APPROVAL_STATUS          VARCHAR(40) NOT NULL,
    APPLY_STATUS             VARCHAR(40) NOT NULL,
    BLOCK_REASON             VARCHAR(1000),
    APPROVED_BY              VARCHAR(80),
    APPROVED_AT              DATETIME,
    REJECTED_BY              VARCHAR(80),
    REJECTED_AT              DATETIME,
    CREATED_AT               DATETIME NOT NULL,
    UPDATED_AT               DATETIME NOT NULL,
    CREATED_BY               VARCHAR(80),
    UPDATED_BY               VARCHAR(80)
);

CREATE INDEX IX_DEPLOYABLE_DB_PATCH_QUEUE_STATUS
    ON DEPLOYABLE_DB_PATCH_QUEUE (PROJECT_ID, APPROVAL_STATUS, APPLY_STATUS, CREATED_AT);

CREATE INDEX IX_DEPLOYABLE_DB_PATCH_QUEUE_TARGET
    ON DEPLOYABLE_DB_PATCH_QUEUE (TARGET_TABLE_NAME, TARGET_ENV, CREATED_AT);

CREATE TABLE DEPLOYABLE_DB_PATCH_RESULT (
    RESULT_ID                VARCHAR(120) PRIMARY KEY,
    QUEUE_ID                 VARCHAR(120) NOT NULL,
    EXECUTION_BATCH_ID       VARCHAR(120) NOT NULL,
    PROJECT_ID               VARCHAR(80) NOT NULL,
    TARGET_ENV               VARCHAR(40) NOT NULL,
    EXECUTION_STATUS         VARCHAR(40) NOT NULL,
    EXECUTION_MESSAGE        VARCHAR(2000),
    RESULT_SQL_PREVIEW       CLOB,
    CHECKSUM_SHA256          VARCHAR(128),
    DB_PATCH_HISTORY_ID      VARCHAR(120),
    STARTED_AT               DATETIME NOT NULL,
    FINISHED_AT              DATETIME,
    EXECUTED_BY              VARCHAR(80),
    CREATED_AT               DATETIME NOT NULL
);

CREATE INDEX IX_DEPLOYABLE_DB_PATCH_RESULT_QUEUE
    ON DEPLOYABLE_DB_PATCH_RESULT (QUEUE_ID, STARTED_AT);

CREATE INDEX IX_DEPLOYABLE_DB_PATCH_RESULT_BATCH
    ON DEPLOYABLE_DB_PATCH_RESULT (EXECUTION_BATCH_ID, STARTED_AT);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-common-class-code',
    'COMTCCMMNCLCODE',
    'AUTO_QUEUE',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Common class-code governance is environment-independent metadata.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-dept-author-rel',
    'COMTNDEPTAUTHORRELATE',
    'MANUAL_APPROVAL',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Department-role mapping is deployable metadata but should remain operator-approved.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-emplyr-scrty',
    'COMTNEMPLYRSCRTYESTBS',
    'BLOCKED',
    '["INSERT","UPDATE","DELETE"]',
    'SENSITIVE_MEMBER',
    'NONE',
    'Y',
    'Live user or administrator security assignments must not be promoted through metadata patch automation.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-common-code',
    'COMTCCMMNCODE',
    'AUTO_QUEUE',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Common code governance is environment-independent metadata.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-menu-info',
    'COMTNMENUINFO',
    'MANUAL_APPROVAL',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Menu metadata is deployable but should remain operator-approved.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-menu-feature',
    'COMTNMENUFUNCTIONINFO',
    'MANUAL_APPROVAL',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Menu feature metadata is deployable but should remain operator-approved.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-feature-author',
    'COMTNAUTHORINFO',
    'MANUAL_APPROVAL',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'UPSERT_DELETE_BY_KEY',
    'Y',
    'Authority metadata is deployable but high-impact, so approval is required.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-author-feature-rel',
    'COMTNAUTHORFUNCTIONRELATE',
    'MANUAL_APPROVAL',
    '["INSERT","UPDATE","DELETE"]',
    'STANDARD_ADMIN',
    'RELATION_REPLACE_BY_OWNER',
    'Y',
    'Authority-feature relation metadata is deployable but should remain operator-approved.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);

INSERT INTO DB_CHANGE_PROMOTION_POLICY (
    POLICY_ID, TABLE_NAME, POLICY_CODE, CHANGE_TYPES_JSON, MASKING_PROFILE_CODE, SQL_RENDER_MODE,
    ACTIVE_YN, POLICY_REASON, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
) VALUES (
    'db-policy-member',
    'COMTNNTERPRISEMBER',
    'BLOCKED',
    '["INSERT","UPDATE","DELETE"]',
    'SENSITIVE_MEMBER',
    'NONE',
    'Y',
    'Live member data must not be promoted through metadata patch automation.',
    CURRENT_DATETIME,
    CURRENT_DATETIME,
    'codex',
    'codex'
);
