CREATE TABLE ARTIFACT_LOCK (
    PROJECT_ID       VARCHAR(80) NOT NULL,
    RELEASE_UNIT_ID  VARCHAR(120) NOT NULL,
    GROUP_ID         VARCHAR(160) NOT NULL,
    ARTIFACT_ID      VARCHAR(160) NOT NULL,
    ARTIFACT_VERSION VARCHAR(80) NOT NULL,
    ARTIFACT_SHA256  VARCHAR(128) NOT NULL,
    LOCK_SOURCE      VARCHAR(40),
    CREATED_AT       DATETIME NOT NULL,
    PRIMARY KEY (PROJECT_ID, RELEASE_UNIT_ID, GROUP_ID, ARTIFACT_ID)
);

CREATE INDEX IX_ARTIFACT_LOCK_PROJECT
    ON ARTIFACT_LOCK (PROJECT_ID, CREATED_AT);

CREATE TABLE PROJECT_COMPATIBILITY_RUN (
    RUN_ID                    VARCHAR(120) PRIMARY KEY,
    PROJECT_ID                VARCHAR(80) NOT NULL,
    SOURCE_RELEASE_UNIT_ID    VARCHAR(120),
    TARGET_COMMON_VERSION     VARCHAR(80),
    BUILD_STATUS              VARCHAR(40) NOT NULL,
    ADAPTER_CONTRACT_STATUS   VARCHAR(40) NOT NULL,
    DB_DIFF_STATUS            VARCHAR(40) NOT NULL,
    SMOKE_STATUS              VARCHAR(40) NOT NULL,
    COMPATIBILITY_STATUS      VARCHAR(40) NOT NULL,
    BLOCKING_REASON           VARCHAR(4000),
    ROLLBACK_RELEASE_UNIT_ID  VARCHAR(120),
    TESTED_AT                 DATETIME NOT NULL,
    TESTED_BY                 VARCHAR(80)
);

CREATE INDEX IX_PROJECT_COMPATIBILITY_RUN_PROJECT
    ON PROJECT_COMPATIBILITY_RUN (PROJECT_ID, TESTED_AT);
