-- Carbonet 5.0 selective auth-token backport.
-- Purpose: replace the upstream Redis token registry with a CUBRID-backed store.
-- Apply once before enforcing server-side refresh-token revocation.

CREATE TABLE COMTNAUTHTOKENSTORE (
    USER_ID            VARCHAR(80)  NOT NULL,
    USER_SE            VARCHAR(10),
    TOKEN_KEY          VARCHAR(128) NOT NULL,
    ACCESS_TOKEN_HASH  VARCHAR(128),
    REFRESH_TOKEN_HASH VARCHAR(128) NOT NULL,
    EXPIRATION_AT      DATETIME     NOT NULL,
    CLIENT_IP          VARCHAR(80),
    USER_AGENT         VARCHAR(500),
    LAST_USED_AT       DATETIME,
    CREATED_AT         DATETIME     NOT NULL DEFAULT CURRENT_DATETIME,
    UPDATED_AT         DATETIME     NOT NULL DEFAULT CURRENT_DATETIME,
    PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX UX_COMTNAUTHTOKENSTORE_TOKEN ON COMTNAUTHTOKENSTORE (TOKEN_KEY);
CREATE INDEX IDX_COMTNAUTHTOKENSTORE_EXP ON COMTNAUTHTOKENSTORE (EXPIRATION_AT);

-- Optional cleanup job:
-- DELETE FROM COMTNAUTHTOKENSTORE WHERE EXPIRATION_AT <= CURRENT_DATETIME;
