-- Emission survey admin: allow classification-specific case persistence
-- Scope: /admin/emission/survey-admin
-- Date: 2026-04-07

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_MAJOR_CODE  VARCHAR(20);

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_MAJOR_LABEL VARCHAR(200);

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_MIDDLE_CODE VARCHAR(20);

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_MIDDLE_LABEL VARCHAR(200);

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_SMALL_CODE VARCHAR(20);

ALTER TABLE ADMIN_EMISSION_SURVEY_CASE
    ADD COLUMN LCI_SMALL_LABEL VARCHAR(200);

UPDATE ADMIN_EMISSION_SURVEY_CASE
SET LCI_MAJOR_CODE = COALESCE(LCI_MAJOR_CODE, ''),
    LCI_MAJOR_LABEL = COALESCE(LCI_MAJOR_LABEL, ''),
    LCI_MIDDLE_CODE = COALESCE(LCI_MIDDLE_CODE, ''),
    LCI_MIDDLE_LABEL = COALESCE(LCI_MIDDLE_LABEL, ''),
    LCI_SMALL_CODE = COALESCE(LCI_SMALL_CODE, ''),
    LCI_SMALL_LABEL = COALESCE(LCI_SMALL_LABEL, '');

DROP INDEX IDX_ADMIN_EMISSION_SURVEY_CASE_01 ON ADMIN_EMISSION_SURVEY_CASE;

CREATE UNIQUE INDEX IDX_ADMIN_EMISSION_SURVEY_CASE_01
    ON ADMIN_EMISSION_SURVEY_CASE (SECTION_CODE, CASE_CODE, LCI_MAJOR_CODE, LCI_MIDDLE_CODE, LCI_SMALL_CODE);

CREATE INDEX IDX_ADMIN_EMISSION_SURVEY_CASE_03
    ON ADMIN_EMISSION_SURVEY_CASE (LCI_MAJOR_CODE, LCI_MIDDLE_CODE, LCI_SMALL_CODE, CASE_CODE, LAST_SAVED_AT);
