-- Normalize attachment-management VIEW feature to the ADMIN_A0040104_VIEW pattern.
--
-- Target menu:
-- - A0040104 / /admin/content/file

-- 1) Pre-check
SELECT m.MENU_CODE, m.MENU_URL, f.FEATURE_CODE, f.FEATURE_NM, f.FEATURE_NM_EN, f.USE_AT
FROM COMTNMENUINFO m
LEFT JOIN COMTNMENUFUNCTIONINFO f
  ON f.MENU_CODE = m.MENU_CODE
WHERE m.MENU_URL = '/admin/content/file'
ORDER BY f.FEATURE_CODE;

SELECT AUTHOR_CODE, FEATURE_CODE
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE IN ('A0040104_VIEW', 'ADMIN_A0040104_VIEW')
ORDER BY FEATURE_CODE, AUTHOR_CODE;

-- 2) Copy missing role mappings to the canonical feature code
INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT
    r.AUTHOR_CODE,
    'ADMIN_A0040104_VIEW',
    'N',
    CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE r
WHERE r.FEATURE_CODE = 'A0040104_VIEW'
  AND EXISTS (
      SELECT 1
      FROM COMTNMENUFUNCTIONINFO f
      WHERE f.FEATURE_CODE = 'ADMIN_A0040104_VIEW'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE r2
      WHERE r2.AUTHOR_CODE = r.AUTHOR_CODE
        AND r2.FEATURE_CODE = 'ADMIN_A0040104_VIEW'
  );

-- 3) Remove the duplicate legacy feature code
DELETE FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE = 'A0040104_VIEW';

DELETE FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE = 'A0040104_VIEW';

-- 4) Post-check
SELECT m.MENU_CODE, m.MENU_URL, f.FEATURE_CODE, f.FEATURE_NM, f.FEATURE_NM_EN, f.USE_AT
FROM COMTNMENUINFO m
LEFT JOIN COMTNMENUFUNCTIONINFO f
  ON f.MENU_CODE = m.MENU_CODE
WHERE m.MENU_URL = '/admin/content/file'
ORDER BY f.FEATURE_CODE;

SELECT AUTHOR_CODE, FEATURE_CODE
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE = 'ADMIN_A0040104_VIEW'
ORDER BY AUTHOR_CODE;
