-- CUBRID-safe emission variable management menu registration
-- Parent tree: A002 (배출/인증) > A00201 (배출)
-- New page: A0020107 (배출 변수 관리)

-- Pre-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A0020107')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A0020107')
   OR MENU_URL = '/admin/emission/management'
ORDER BY MENU_CODE;

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0020107_VIEW',
    'A0020107_SESSION_SAVE',
    'A0020107_CALCULATE',
    'A0020107_FACTOR_VIEW'
)
ORDER BY FEATURE_CODE;

-- Detail code
INSERT INTO COMTCCMMNDETAILCODE (
    CODE_ID,
    CODE,
    CODE_NM,
    CODE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    FRST_REGISTER_ID
)
SELECT 'AMENU1', 'A0020107', '배출 변수 관리', 'Emission Variable Management', 'Y', CURRENT_DATETIME, 'codex' FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTCCMMNDETAILCODE
    WHERE CODE_ID = 'AMENU1'
      AND CODE = 'A0020107'
);

UPDATE COMTCCMMNDETAILCODE
SET CODE_NM = '배출 변수 관리',
    CODE_DC = 'Emission Variable Management',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE CODE_ID = 'AMENU1'
  AND CODE = 'A0020107';

-- Menu info
INSERT INTO COMTNMENUINFO (
    MENU_CODE,
    MENU_NM,
    MENU_NM_EN,
    MENU_URL,
    MENU_ICON,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', '배출 변수 관리', 'Emission Variable Management', '/admin/emission/management', 'calculate', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUINFO
    WHERE MENU_CODE = 'A0020107'
);

UPDATE COMTNMENUINFO
SET MENU_NM = '배출 변수 관리',
    MENU_NM_EN = 'Emission Variable Management',
    MENU_URL = '/admin/emission/management',
    MENU_ICON = 'calculate',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0020107';

-- Menu order
INSERT INTO COMTNMENUORDER (
    MENU_CODE,
    SORT_ORDR,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', 7, CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUORDER
    WHERE MENU_CODE = 'A0020107'
);

UPDATE COMTNMENUORDER
SET SORT_ORDR = 7,
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE MENU_CODE = 'A0020107';

-- Features
INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', 'A0020107_VIEW', '배출 변수 관리 조회', 'View Emission Variable Management', '배출 변수 관리 화면 기본 VIEW 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0020107_VIEW'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', 'A0020107_SESSION_SAVE', '입력 세션 저장', 'Save Emission Input Session', '배출 변수 입력 세션 저장 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0020107_SESSION_SAVE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', 'A0020107_CALCULATE', '배출량 계산 실행', 'Run Emission Calculation', '배출 변수 계산 실행 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0020107_CALCULATE'
);

INSERT INTO COMTNMENUFUNCTIONINFO (
    MENU_CODE,
    FEATURE_CODE,
    FEATURE_NM,
    FEATURE_NM_EN,
    FEATURE_DC,
    USE_AT,
    FRST_REGIST_PNTTM,
    LAST_UPDT_PNTTM
)
SELECT 'A0020107', 'A0020107_FACTOR_VIEW', '기본계수 조회', 'View Default Factors', '배출 기본계수 조회 권한', 'Y', CURRENT_DATETIME, CURRENT_DATETIME FROM db_root
WHERE NOT EXISTS (
    SELECT 1
    FROM COMTNMENUFUNCTIONINFO
    WHERE FEATURE_CODE = 'A0020107_FACTOR_VIEW'
);

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0020107',
    FEATURE_NM = '배출 변수 관리 조회',
    FEATURE_NM_EN = 'View Emission Variable Management',
    FEATURE_DC = '배출 변수 관리 화면 기본 VIEW 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0020107_VIEW';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0020107',
    FEATURE_NM = '입력 세션 저장',
    FEATURE_NM_EN = 'Save Emission Input Session',
    FEATURE_DC = '배출 변수 입력 세션 저장 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0020107_SESSION_SAVE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0020107',
    FEATURE_NM = '배출량 계산 실행',
    FEATURE_NM_EN = 'Run Emission Calculation',
    FEATURE_DC = '배출 변수 계산 실행 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0020107_CALCULATE';

UPDATE COMTNMENUFUNCTIONINFO
SET MENU_CODE = 'A0020107',
    FEATURE_NM = '기본계수 조회',
    FEATURE_NM_EN = 'View Default Factors',
    FEATURE_DC = '배출 기본계수 조회 권한',
    USE_AT = 'Y',
    LAST_UPDT_PNTTM = CURRENT_DATETIME
WHERE FEATURE_CODE = 'A0020107_FACTOR_VIEW';

-- Copy default role relations from verification view
INSERT INTO COMTNAUTHORFUNCTIONRELATE (
    AUTHOR_CODE,
    FEATURE_CODE,
    GRANT_AUTHORITY_YN,
    CREAT_DT
)
SELECT src.AUTHOR_CODE, 'A0020107_VIEW', src.GRANT_AUTHORITY_YN, CURRENT_DATETIME
FROM COMTNAUTHORFUNCTIONRELATE src
WHERE src.FEATURE_CODE = 'A0020104_VIEW'
  AND NOT EXISTS (
      SELECT 1
      FROM COMTNAUTHORFUNCTIONRELATE x
      WHERE x.AUTHOR_CODE = src.AUTHOR_CODE
        AND x.FEATURE_CODE = 'A0020107_VIEW'
  );

-- Post-check
SELECT CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT
FROM COMTCCMMNDETAILCODE
WHERE CODE_ID = 'AMENU1'
  AND CODE IN ('A0020107')
ORDER BY CODE;

SELECT MENU_CODE, MENU_URL, MENU_NM, MENU_NM_EN, MENU_ICON
FROM COMTNMENUINFO
WHERE MENU_CODE IN ('A0020107')
ORDER BY MENU_CODE;

SELECT MENU_CODE, SORT_ORDR
FROM COMTNMENUORDER
WHERE MENU_CODE IN ('A0020107');

SELECT MENU_CODE, FEATURE_CODE, FEATURE_NM, FEATURE_NM_EN
FROM COMTNMENUFUNCTIONINFO
WHERE FEATURE_CODE IN (
    'A0020107_VIEW',
    'A0020107_SESSION_SAVE',
    'A0020107_CALCULATE',
    'A0020107_FACTOR_VIEW'
)
ORDER BY FEATURE_CODE;

SELECT AUTHOR_CODE, FEATURE_CODE, GRANT_AUTHORITY_YN
FROM COMTNAUTHORFUNCTIONRELATE
WHERE FEATURE_CODE = 'A0020107_VIEW'
ORDER BY AUTHOR_CODE;
