-- Banner management sidecar metadata for React admin migration.
-- Apply after the baseline COMTNBANNER table already exists.

CREATE TABLE COMTNBANNERMETA (
    BANNER_ID            CHAR(20)     NOT NULL,
    BANNER_NM_EN         VARCHAR(180) NULL,
    PLACEMENT_KO         VARCHAR(120) NULL,
    PLACEMENT_EN         VARCHAR(120) NULL,
    STATUS_CODE          VARCHAR(20)  NULL,
    START_AT             DATETIME     NULL,
    END_AT               DATETIME     NULL,
    CLICK_COUNT          NUMERIC(10)  NULL,
    NOTE_EN              VARCHAR(600) NULL,
    FRST_REGISTER_ID     VARCHAR(60)  NULL,
    FRST_REGIST_PNTTM    DATETIME     NULL,
    LAST_UPDUSR_ID       VARCHAR(60)  NULL,
    LAST_UPDT_PNTTM      DATETIME     NULL,
CONSTRAINT COMTNBANNERMETA_PK PRIMARY KEY (BANNER_ID)
);

ALTER TABLE COMTNBANNERMETA
    ADD CONSTRAINT FK_COMTNBANNERMETA_01
    FOREIGN KEY (BANNER_ID)
    REFERENCES COMTNBANNER (BANNER_ID);
