-- Carbonet Admin Screen Builder Phase 1 MVP
-- Draft schema only. Validate naming and physical DB conventions before production migration.

CREATE TABLE COMTNSCREENBUILDERDEF (
    BUILDER_ID            VARCHAR(40)  NOT NULL,
    PAGE_ID               VARCHAR(100) NOT NULL,
    MENU_CODE             VARCHAR(8)   NOT NULL,
    TEMPLATE_TYPE         VARCHAR(40)  NOT NULL,
    STATUS                VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    CURRENT_VERSION_ID    VARCHAR(40),
    USE_AT                CHAR(1)      NOT NULL DEFAULT 'Y',
    REGIST_PNTTM          VARCHAR(20),
    FRST_REGISTER_ID      VARCHAR(50),
    LAST_UPDT_PNTTM       VARCHAR(20),
    LAST_UPDUSR_ID        VARCHAR(50),
    PRIMARY KEY (BUILDER_ID)
);

CREATE UNIQUE INDEX IDX_SCREENBUILDERDEF_MENU_CODE
    ON COMTNSCREENBUILDERDEF (MENU_CODE);

CREATE TABLE COMTNSCREENBUILDERVER (
    VERSION_ID            VARCHAR(40)  NOT NULL,
    BUILDER_ID            VARCHAR(40)  NOT NULL,
    VERSION_NO            INTEGER      NOT NULL,
    VERSION_STATUS        VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    DRAFT_JSON            CLOB         NOT NULL,
    VALIDATION_STATUS     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    VALIDATION_MESSAGE    CLOB,
    PUBLISHED_YN          CHAR(1)      NOT NULL DEFAULT 'N',
    REGIST_PNTTM          VARCHAR(20),
    FRST_REGISTER_ID      VARCHAR(50),
    PRIMARY KEY (VERSION_ID)
);

CREATE UNIQUE INDEX IDX_SCREENBUILDERVER_BUILDER_VERSION
    ON COMTNSCREENBUILDERVER (BUILDER_ID, VERSION_NO);

CREATE TABLE COMTNSCREENBUILDERNODE (
    NODE_ID               VARCHAR(40)  NOT NULL,
    VERSION_ID            VARCHAR(40)  NOT NULL,
    PARENT_NODE_ID        VARCHAR(40),
    COMPONENT_TYPE        VARCHAR(40)  NOT NULL,
    SLOT_NAME             VARCHAR(60),
    SORT_ORDR             INTEGER      NOT NULL DEFAULT 0,
    PROPS_JSON            CLOB         NOT NULL,
    PRIMARY KEY (NODE_ID)
);

CREATE INDEX IDX_SCREENBUILDERNODE_VERSION
    ON COMTNSCREENBUILDERNODE (VERSION_ID, SORT_ORDR);

CREATE TABLE COMTNSCREENBUILDEREVENT (
    EVENT_BINDING_ID      VARCHAR(40)  NOT NULL,
    VERSION_ID            VARCHAR(40)  NOT NULL,
    NODE_ID               VARCHAR(40)  NOT NULL,
    EVENT_NAME            VARCHAR(40)  NOT NULL,
    ACTION_TYPE           VARCHAR(40)  NOT NULL,
    ACTION_CONFIG_JSON    CLOB         NOT NULL,
    PRIMARY KEY (EVENT_BINDING_ID)
);

CREATE INDEX IDX_SCREENBUILDEREVENT_VERSION
    ON COMTNSCREENBUILDEREVENT (VERSION_ID, NODE_ID);

-- Phase 1 linkage extension idea for menu workspace overlay:
-- add builder flags to an overlay table or service layer, not directly to COMTNMENUINFO.
--
-- Example overlay view payload fields:
--   builderManagedYn
--   builderId
--   currentVersionStatus
--   previewUrl
--   editorUrl
