-- Carbonet platform control plane draft schema
-- Generated on 2026-03-15
-- Target DB: CUBRID-compatible SQL draft

CREATE TABLE PROJECT_REGISTRY (
    PROJECT_ID VARCHAR(60) NOT NULL,
    PROJECT_CODE VARCHAR(60) NOT NULL,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    ROUTE_PREFIX VARCHAR(200),
    DOMAIN_HOST VARCHAR(300),
    DEPLOYMENT_TARGET VARCHAR(200),
    JAVA_VERSION VARCHAR(40),
    DB_DRIVER_VERSION VARCHAR(80),
    PLATFORM_VERSION VARCHAR(40) NOT NULL,
    PROJECT_MODULE_VERSION VARCHAR(40) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    OWNER_ADMIN_ID VARCHAR(60),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (PROJECT_ID)
);

CREATE UNIQUE INDEX UQ_PROJECT_REGISTRY_CODE ON PROJECT_REGISTRY (PROJECT_CODE);

CREATE TABLE COMMON_MODULE_REGISTRY (
    COMMON_MODULE_ID VARCHAR(80) NOT NULL,
    COMMON_MODULE_TYPE VARCHAR(40) NOT NULL,
    MODULE_NAME VARCHAR(200) NOT NULL,
    ARTIFACT_COORDINATE VARCHAR(300),
    VERSION VARCHAR(40) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    COMPATIBILITY_POLICY VARCHAR(100),
    PUBLISHED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (COMMON_MODULE_ID)
);

CREATE INDEX IDX_COMMON_MODULE_TYPE ON COMMON_MODULE_REGISTRY (COMMON_MODULE_TYPE);

CREATE TABLE INSTALL_UNIT (
    PACKAGE_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    MENU_CODE VARCHAR(30),
    PAGE_ID VARCHAR(100),
    PACKAGE_NAME VARCHAR(200) NOT NULL,
    MODULE_TYPE VARCHAR(40),
    STATUS VARCHAR(30) NOT NULL,
    COPY_SOURCE_PACKAGE_ID VARCHAR(80),
    PLATFORM_VERSION VARCHAR(40) NOT NULL,
    MODULE_VERSION VARCHAR(40) NOT NULL,
    INSTALLED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (PACKAGE_ID)
);

CREATE INDEX IDX_INSTALL_UNIT_PROJECT_ID ON INSTALL_UNIT (PROJECT_ID);
CREATE INDEX IDX_INSTALL_UNIT_MENU_CODE ON INSTALL_UNIT (MENU_CODE);

CREATE TABLE INSTALL_UNIT_COMMON_MODULE (
    MAP_ID VARCHAR(80) NOT NULL,
    PACKAGE_ID VARCHAR(80) NOT NULL,
    COMMON_MODULE_ID VARCHAR(80) NOT NULL,
    VERSION VARCHAR(40) NOT NULL,
    REQUIRED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    USAGE_MODE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (MAP_ID)
);

CREATE INDEX IDX_INSTALL_UNIT_COMMON_PACKAGE_ID ON INSTALL_UNIT_COMMON_MODULE (PACKAGE_ID);
CREATE INDEX IDX_INSTALL_UNIT_COMMON_MODULE_ID ON INSTALL_UNIT_COMMON_MODULE (COMMON_MODULE_ID);

CREATE TABLE RESOURCE_REGISTRY (
    RESOURCE_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60),
    PACKAGE_ID VARCHAR(80),
    RESOURCE_TYPE VARCHAR(40) NOT NULL,
    OWNER_SCOPE VARCHAR(30) NOT NULL,
    USAGE_MODE VARCHAR(30) NOT NULL,
    LOGICAL_NAME VARCHAR(200) NOT NULL,
    PHYSICAL_NAME VARCHAR(300),
    SOURCE_PATH VARCHAR(1000),
    DB_OBJECT_NAME VARCHAR(200),
    STATUS VARCHAR(30) NOT NULL,
    LAST_VERIFIED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (RESOURCE_ID)
);

CREATE INDEX IDX_RESOURCE_REGISTRY_PROJECT_ID ON RESOURCE_REGISTRY (PROJECT_ID);
CREATE INDEX IDX_RESOURCE_REGISTRY_PACKAGE_ID ON RESOURCE_REGISTRY (PACKAGE_ID);
CREATE INDEX IDX_RESOURCE_REGISTRY_TYPE ON RESOURCE_REGISTRY (RESOURCE_TYPE);
CREATE INDEX IDX_RESOURCE_REGISTRY_DB_OBJECT ON RESOURCE_REGISTRY (DB_OBJECT_NAME);

CREATE TABLE RESOURCE_DEPENDENCY (
    DEPENDENCY_ID VARCHAR(80) NOT NULL,
    PARENT_RESOURCE_ID VARCHAR(80) NOT NULL,
    CHILD_RESOURCE_ID VARCHAR(80) NOT NULL,
    DEPENDENCY_TYPE VARCHAR(40) NOT NULL,
    REQUIRED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    DELETE_ORDER INTEGER DEFAULT 0 NOT NULL,
    SHARED_BLOCK_REASON VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (DEPENDENCY_ID)
);

CREATE INDEX IDX_RESOURCE_DEP_PARENT ON RESOURCE_DEPENDENCY (PARENT_RESOURCE_ID);
CREATE INDEX IDX_RESOURCE_DEP_CHILD ON RESOURCE_DEPENDENCY (CHILD_RESOURCE_ID);

CREATE TABLE PROJECT_DB_MIGRATION_STATUS (
    STATUS_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    ENVIRONMENT_CODE VARCHAR(40) NOT NULL,
    DB_MIGRATION_VERSION VARCHAR(40) NOT NULL,
    PLATFORM_VERSION VARCHAR(40) NOT NULL,
    PROJECT_MODULE_VERSION VARCHAR(40) NOT NULL,
    LAST_APPLIED_AT DATETIME,
    LAST_VERIFIED_AT DATETIME,
    STATUS VARCHAR(30) NOT NULL,
    DRIFT_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (STATUS_ID)
);

CREATE INDEX IDX_PROJECT_DB_MIGRATION_PROJECT_ID ON PROJECT_DB_MIGRATION_STATUS (PROJECT_ID);
CREATE INDEX IDX_PROJECT_DB_MIGRATION_ENV ON PROJECT_DB_MIGRATION_STATUS (ENVIRONMENT_CODE);

CREATE TABLE RELEASE_UNIT (
    RELEASE_UNIT_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    ENVIRONMENT_CODE VARCHAR(40) NOT NULL,
    PLATFORM_VERSION VARCHAR(40) NOT NULL,
    PROJECT_MODULE_VERSION VARCHAR(40) NOT NULL,
    DB_MIGRATION_VERSION VARCHAR(40) NOT NULL,
    API_CONTRACT_VERSION VARCHAR(40),
    APPROVAL_STATUS VARCHAR(30) NOT NULL,
    APPROVED_BY VARCHAR(60),
    APPROVED_AT DATETIME,
    APPLIED_AT DATETIME,
    ROLLBACK_READY_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (RELEASE_UNIT_ID)
);

CREATE INDEX IDX_RELEASE_UNIT_PROJECT_ID ON RELEASE_UNIT (PROJECT_ID);
CREATE INDEX IDX_RELEASE_UNIT_ENV ON RELEASE_UNIT (ENVIRONMENT_CODE);

CREATE TABLE PROJECT_DB_CONNECTION (
    CONNECTION_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    ENVIRONMENT_CODE VARCHAR(40) NOT NULL,
    DB_HOST VARCHAR(300),
    DB_PORT VARCHAR(20),
    DB_NAME VARCHAR(200),
    USERNAME_REF VARCHAR(120),
    ACCESS_POLICY VARCHAR(40),
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (CONNECTION_ID)
);

CREATE INDEX IDX_PROJECT_DB_CONNECTION_PROJECT_ID ON PROJECT_DB_CONNECTION (PROJECT_ID);

CREATE TABLE DELETE_PLAN (
    DELETE_PLAN_ID VARCHAR(80) NOT NULL,
    PROJECT_ID VARCHAR(60) NOT NULL,
    PACKAGE_ID VARCHAR(80),
    PLAN_STATUS VARCHAR(30) NOT NULL,
    REQUESTED_BY VARCHAR(60),
    APPROVED_BY VARCHAR(60),
    REQUESTED_AT DATETIME,
    APPROVED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (DELETE_PLAN_ID)
);

CREATE TABLE DELETE_PLAN_ITEM (
    DELETE_PLAN_ITEM_ID VARCHAR(80) NOT NULL,
    DELETE_PLAN_ID VARCHAR(80) NOT NULL,
    RESOURCE_ID VARCHAR(80),
    TARGET_TYPE VARCHAR(40) NOT NULL,
    TARGET_NAME VARCHAR(300),
    ACTION_TYPE VARCHAR(40) NOT NULL,
    BLOCK_REASON VARCHAR(1000),
    DELETE_ORDER INTEGER DEFAULT 0 NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (DELETE_PLAN_ITEM_ID)
);

CREATE INDEX IDX_DELETE_PLAN_ITEM_PLAN_ID ON DELETE_PLAN_ITEM (DELETE_PLAN_ID);

-- Builder overlay and compatibility control-plane extension lives in:
-- docs/sql/20260324_builder_overlay_and_compatibility_control_plane.sql
