-- Project version governance draft
-- Generated on 2026-04-08 for artifact registry and adapter-safe common upgrade flow

CREATE TABLE IF NOT EXISTS ARTIFACT_VERSION_REGISTRY (
    ARTIFACT_VERSION_ID        VARCHAR(80) PRIMARY KEY,
    ARTIFACT_ID                VARCHAR(120) NOT NULL,
    ARTIFACT_TYPE              VARCHAR(40) NOT NULL,
    ARTIFACT_FAMILY            VARCHAR(40) NOT NULL,
    ARTIFACT_VERSION           VARCHAR(40) NOT NULL,
    GROUP_LINE                 VARCHAR(60),
    STORAGE_KEY                VARCHAR(255) NOT NULL,
    CHECKSUM_SHA256            VARCHAR(64) NOT NULL,
    COMMON_CORE_VERSION        VARCHAR(40),
    ADAPTER_CONTRACT_VERSION   VARCHAR(40),
    API_CONTRACT_VERSION       VARCHAR(40),
    MANIFEST_CONTRACT_VERSION  VARCHAR(40),
    CAPABILITY_CATALOG_VERSION VARCHAR(40),
    COMPATIBILITY_STATUS       VARCHAR(30) NOT NULL,
    PUBLISHED_YN               CHAR(1) DEFAULT 'N' NOT NULL,
    BUILT_AT                   DATETIME,
    PUBLISHED_AT               DATETIME,
    PUBLISHED_BY               VARCHAR(80)
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_ARTIFACT_VERSION_REGISTRY_KEY
    ON ARTIFACT_VERSION_REGISTRY (ARTIFACT_ID, ARTIFACT_VERSION);

CREATE TABLE IF NOT EXISTS PROJECT_ARTIFACT_INSTALL (
    PROJECT_ARTIFACT_INSTALL_ID VARCHAR(80) PRIMARY KEY,
    PROJECT_ID                  VARCHAR(80) NOT NULL,
    ARTIFACT_VERSION_ID         VARCHAR(80) NOT NULL,
    INSTALL_SCOPE               VARCHAR(40) NOT NULL,
    RELEASE_UNIT_ID             VARCHAR(120),
    ACTIVE_YN                   CHAR(1) DEFAULT 'Y' NOT NULL,
    ROLLBACK_TARGET_VERSION     VARCHAR(40),
    INSTALLED_AT                DATETIME,
    INSTALLED_BY                VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS IX_PROJECT_ARTIFACT_INSTALL_PROJECT
    ON PROJECT_ARTIFACT_INSTALL (PROJECT_ID, ACTIVE_YN);

CREATE TABLE IF NOT EXISTS ADAPTER_CHANGE_LOG (
    ADAPTER_CHANGE_ID          VARCHAR(80) PRIMARY KEY,
    PROJECT_ID                 VARCHAR(80) NOT NULL,
    ADAPTER_ARTIFACT_VERSION   VARCHAR(40) NOT NULL,
    ADAPTER_CONTRACT_VERSION   VARCHAR(40) NOT NULL,
    CHANGED_PORT_SET_JSON      TEXT,
    CHANGED_DTO_SET_JSON       TEXT,
    MAPPING_IMPACT_SUMMARY     VARCHAR(1000),
    COMPATIBILITY_CLASS        VARCHAR(40) NOT NULL,
    MIGRATION_REQUIRED_YN      CHAR(1) DEFAULT 'N' NOT NULL,
    RELATED_RELEASE_UNIT_ID    VARCHAR(120),
    RECORDED_AT                DATETIME NOT NULL,
    RECORDED_BY                VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS IX_ADAPTER_CHANGE_LOG_PROJECT
    ON ADAPTER_CHANGE_LOG (PROJECT_ID, RECORDED_AT);

CREATE TABLE IF NOT EXISTS RELEASE_UNIT_REGISTRY (
    RELEASE_UNIT_ID            VARCHAR(120) PRIMARY KEY,
    PROJECT_ID                 VARCHAR(80) NOT NULL,
    RUNTIME_PACKAGE_ID         VARCHAR(120) NOT NULL,
    PROJECT_RUNTIME_VERSION    VARCHAR(40) NOT NULL,
    ADAPTER_ARTIFACT_VERSION   VARCHAR(40),
    ADAPTER_CONTRACT_VERSION   VARCHAR(40),
    COMMON_ARTIFACT_SET_JSON   TEXT,
    PACKAGE_VERSION_SET_JSON   TEXT,
    ROLLBACK_TARGET_RELEASE_ID VARCHAR(120),
    BUILT_AT                   DATETIME,
    APPROVED_AT                DATETIME,
    APPROVED_BY                VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS IX_RELEASE_UNIT_REGISTRY_PROJECT
    ON RELEASE_UNIT_REGISTRY (PROJECT_ID, BUILT_AT);

CREATE TABLE IF NOT EXISTS SERVER_DEPLOYMENT_STATE (
    SERVER_DEPLOYMENT_ID       VARCHAR(80) PRIMARY KEY,
    SERVER_ID                  VARCHAR(80) NOT NULL,
    SERVER_ROLE                VARCHAR(30),
    PROJECT_ID                 VARCHAR(80) NOT NULL,
    RELEASE_UNIT_ID            VARCHAR(120) NOT NULL,
    DEPLOY_TRACE_ID            VARCHAR(120) NOT NULL,
    HEALTH_STATUS              VARCHAR(30),
    DEPLOYED_AT                DATETIME,
    DEPLOYED_BY                VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS IX_SERVER_DEPLOYMENT_STATE_SERVER
    ON SERVER_DEPLOYMENT_STATE (SERVER_ID, PROJECT_ID, DEPLOYED_AT);
