-- Carbonet system observability draft schema
-- Generated on 2026-03-14
-- Target DB: CUBRID-compatible SQL draft

CREATE TABLE TRACE_SESSION (
    TRACE_ID VARCHAR(40) NOT NULL,
    SESSION_ID VARCHAR(100),
    USER_ID VARCHAR(60),
    ACTOR_TYPE VARCHAR(30),
    ENTRY_PAGE_ID VARCHAR(100),
    STARTED_AT DATETIME NOT NULL,
    ENDED_AT DATETIME,
    PRIMARY KEY (TRACE_ID)
);

CREATE TABLE TRACE_EVENT (
    EVENT_ID VARCHAR(40) NOT NULL,
    TRACE_ID VARCHAR(40) NOT NULL,
    SPAN_ID VARCHAR(40),
    PARENT_SPAN_ID VARCHAR(40),
    EVENT_TYPE VARCHAR(40) NOT NULL,
    PAGE_ID VARCHAR(100),
    COMPONENT_ID VARCHAR(120),
    FUNCTION_ID VARCHAR(120),
    API_ID VARCHAR(200),
    RESULT_CODE VARCHAR(30),
    DURATION_MS INTEGER,
    PAYLOAD_SUMMARY CLOB,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_TRACE_EVENT_TRACE_ID ON TRACE_EVENT (TRACE_ID);
CREATE INDEX IDX_TRACE_EVENT_PAGE_ID ON TRACE_EVENT (PAGE_ID);
CREATE INDEX IDX_TRACE_EVENT_API_ID ON TRACE_EVENT (API_ID);
CREATE INDEX IDX_TRACE_EVENT_CREATED_AT ON TRACE_EVENT (CREATED_AT);

CREATE TABLE AUDIT_EVENT (
    AUDIT_ID VARCHAR(40) NOT NULL,
    TRACE_ID VARCHAR(40),
    REQUEST_ID VARCHAR(40),
    ACTOR_ID VARCHAR(60),
    ACTOR_ROLE VARCHAR(60),
    MENU_CODE VARCHAR(30),
    PAGE_ID VARCHAR(100),
    ACTION_CODE VARCHAR(120) NOT NULL,
    ENTITY_TYPE VARCHAR(80),
    ENTITY_ID VARCHAR(120),
    BEFORE_SUMMARY CLOB,
    AFTER_SUMMARY CLOB,
    RESULT_STATUS VARCHAR(30) NOT NULL,
    REASON_SUMMARY VARCHAR(1000),
    IP_ADDRESS VARCHAR(64),
    USER_AGENT VARCHAR(500),
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (AUDIT_ID)
);

CREATE INDEX IDX_AUDIT_EVENT_TRACE_ID ON AUDIT_EVENT (TRACE_ID);
CREATE INDEX IDX_AUDIT_EVENT_ACTOR_ID ON AUDIT_EVENT (ACTOR_ID);
CREATE INDEX IDX_AUDIT_EVENT_MENU_CODE ON AUDIT_EVENT (MENU_CODE);
CREATE INDEX IDX_AUDIT_EVENT_ACTION_CODE ON AUDIT_EVENT (ACTION_CODE);
CREATE INDEX IDX_AUDIT_EVENT_CREATED_AT ON AUDIT_EVENT (CREATED_AT);

CREATE TABLE UI_PAGE_MANIFEST (
    PAGE_ID VARCHAR(100) NOT NULL,
    PAGE_NAME VARCHAR(200) NOT NULL,
    ROUTE_PATH VARCHAR(300) NOT NULL,
    DOMAIN_CODE VARCHAR(30) NOT NULL,
    MENU_CODE VARCHAR(30),
    LAYOUT_VERSION VARCHAR(40) NOT NULL,
    DESIGN_TOKEN_VERSION VARCHAR(40) NOT NULL,
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (PAGE_ID)
);

CREATE TABLE UI_COMPONENT_REGISTRY (
    COMPONENT_ID VARCHAR(120) NOT NULL,
    COMPONENT_NAME VARCHAR(200) NOT NULL,
    COMPONENT_TYPE VARCHAR(60) NOT NULL,
    OWNER_DOMAIN VARCHAR(30),
    PROPS_SCHEMA_JSON CLOB,
    DESIGN_REFERENCE VARCHAR(500),
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (COMPONENT_ID)
);

CREATE TABLE UI_PAGE_COMPONENT_MAP (
    MAP_ID VARCHAR(40) NOT NULL,
    PAGE_ID VARCHAR(100) NOT NULL,
    LAYOUT_ZONE VARCHAR(40) NOT NULL,
    COMPONENT_ID VARCHAR(120) NOT NULL,
    INSTANCE_KEY VARCHAR(120) NOT NULL,
    DISPLAY_ORDER INTEGER DEFAULT 0 NOT NULL,
    CONDITIONAL_RULE_SUMMARY VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (MAP_ID)
);

CREATE INDEX IDX_UI_PAGE_COMPONENT_MAP_PAGE_ID ON UI_PAGE_COMPONENT_MAP (PAGE_ID);
CREATE INDEX IDX_UI_PAGE_COMPONENT_MAP_COMPONENT_ID ON UI_PAGE_COMPONENT_MAP (COMPONENT_ID);

CREATE TABLE UI_HELP_PAGE (
    PAGE_ID VARCHAR(100) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    SUMMARY VARCHAR(2000),
    HELP_VERSION VARCHAR(40) NOT NULL,
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (PAGE_ID)
);

CREATE TABLE UI_HELP_ITEM (
    ITEM_ID VARCHAR(120) NOT NULL,
    PAGE_ID VARCHAR(100) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    BODY VARCHAR(4000) NOT NULL,
    ANCHOR_SELECTOR VARCHAR(500),
    DISPLAY_ORDER INTEGER DEFAULT 0 NOT NULL,
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    PLACEMENT VARCHAR(20) DEFAULT 'top' NOT NULL,
    IMAGE_URL VARCHAR(1000),
    ICON_NAME VARCHAR(80),
    HIGHLIGHT_STYLE VARCHAR(30) DEFAULT 'focus' NOT NULL,
    CTA_LABEL VARCHAR(120),
    CTA_URL VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

CREATE INDEX IDX_UI_HELP_ITEM_PAGE_ID ON UI_HELP_ITEM (PAGE_ID);
