import { ENVIRONMENT_MANAGEMENT_PAGE_UNITS, ENVIRONMENT_MANAGEMENT_ROUTE_UNITS } from "../../../features/environment-management/environmentManagementPageUnit";
import { SCREEN_BUILDER_PAGE_UNITS, SCREEN_BUILDER_ROUTE_UNITS } from "../../../features/screen-builder/screenBuilderPageUnit";
import { PLATFORM_FOUNDATION_PAGE_UNITS, PLATFORM_FOUNDATION_ROUTE_UNITS } from "./platformFoundationRouteUnits";

export const PLATFORM_ROUTE_DEFINITION_FAMILIES = [
  PLATFORM_FOUNDATION_ROUTE_UNITS,
  ENVIRONMENT_MANAGEMENT_ROUTE_UNITS,
  SCREEN_BUILDER_ROUTE_UNITS
] as const;

export const PLATFORM_PAGE_UNIT_FAMILIES = [
  PLATFORM_FOUNDATION_PAGE_UNITS,
  ENVIRONMENT_MANAGEMENT_PAGE_UNITS,
  SCREEN_BUILDER_PAGE_UNITS
] as const;

export type PlatformRouteId = (typeof PLATFORM_ROUTE_DEFINITION_FAMILIES)[number][number]["id"];
