import type { RouteUnitDefinition } from "../../../framework/routes/pageUnitTypes";

export const ADMIN_SYSTEM_ROUTE_DEFINITIONS = [
  { id: "system-code", label: "시스템 코드", group: "admin", koPath: "/admin/system/code", enPath: "/en/admin/system/code" },
  { id: "page-management", label: "화면 관리", group: "admin", koPath: "/admin/system/page-management", enPath: "/en/admin/system/page-management" },
  { id: "function-management", label: "기능 관리", group: "admin", koPath: "/admin/system/feature-management", enPath: "/en/admin/system/feature-management" },
  { id: "menu-management", label: "메뉴 관리", group: "admin", koPath: "/admin/system/menu", enPath: "/en/admin/system/menu" },
  { id: "faq-menu-management", label: "FAQ 메뉴 관리", group: "admin", koPath: "/admin/content/menu", enPath: "/en/admin/content/menu" },
  { id: "full-stack-management", label: "풀스택 관리", group: "admin", koPath: "/admin/system/full-stack-management", enPath: "/en/admin/system/full-stack-management" },
  { id: "infra", label: "인프라", group: "admin", koPath: "/admin/system/infra", enPath: "/en/admin/system/infra" },
  { id: "screen-flow-management", label: "화면 흐름 관리", group: "admin", koPath: "/admin/system/screen-flow-management", enPath: "/en/admin/system/screen-flow-management" },
  { id: "screen-menu-assignment-management", label: "화면-메뉴 귀속 관리", group: "admin", koPath: "/admin/system/screen-menu-assignment-management", enPath: "/en/admin/system/screen-menu-assignment-management" },
  { id: "wbs-management", label: "WBS 관리", group: "admin", koPath: "/admin/system/wbs-management", enPath: "/en/admin/system/wbs-management" },
  { id: "new-page", label: "새 페이지", group: "admin", koPath: "/admin/system/new-page", enPath: "/en/admin/system/new-page" },
  { id: "ip-whitelist", label: "IP 화이트리스트", group: "admin", koPath: "/admin/system/ip_whitelist", enPath: "/en/admin/system/ip_whitelist" },
  { id: "access-history", label: "접속 로그", group: "admin", koPath: "/admin/system/access_history", enPath: "/en/admin/system/access_history" },
  { id: "error-log", label: "에러 로그", group: "admin", koPath: "/admin/system/error-log", enPath: "/en/admin/system/error-log" },
  { id: "login-history", label: "로그인 이력", group: "admin", koPath: "/admin/member/login_history", enPath: "/en/admin/member/login_history" },
  { id: "member-security-history", label: "회원 접근 차단 이력", group: "admin", koPath: "/admin/member/security", enPath: "/en/admin/member/security" },
  { id: "security-history", label: "보안 이력", group: "admin", koPath: "/admin/system/security", enPath: "/en/admin/system/security" },
  { id: "security-policy", label: "보안 정책", group: "admin", koPath: "/admin/system/security-policy", enPath: "/en/admin/system/security-policy" },
  { id: "notification", label: "알림센터", group: "admin", koPath: "/admin/system/notification", enPath: "/en/admin/system/notification" },
  { id: "performance", label: "성능", group: "admin", koPath: "/admin/system/performance", enPath: "/en/admin/system/performance" },
  { id: "external-connection-list", label: "외부 연계 목록", group: "admin", koPath: "/admin/external/connection_list", enPath: "/en/admin/external/connection_list" },
  { id: "external-schema", label: "외부 스키마", group: "admin", koPath: "/admin/external/schema", enPath: "/en/admin/external/schema" },
  { id: "external-keys", label: "외부 인증키 관리", group: "admin", koPath: "/admin/external/keys", enPath: "/en/admin/external/keys" },
  { id: "external-usage", label: "API 사용량", group: "admin", koPath: "/admin/external/usage", enPath: "/en/admin/external/usage" },
  { id: "external-logs", label: "외부 연계 로그", group: "admin", koPath: "/admin/external/logs", enPath: "/en/admin/external/logs" },
  { id: "external-webhooks", label: "웹훅 설정", group: "admin", koPath: "/admin/external/webhooks", enPath: "/en/admin/external/webhooks" },
  { id: "external-sync", label: "동기화 실행", group: "admin", koPath: "/admin/external/sync", enPath: "/en/admin/external/sync" },
  { id: "external-monitoring", label: "연계 모니터링", group: "admin", koPath: "/admin/external/monitoring", enPath: "/en/admin/external/monitoring" },
  { id: "external-maintenance", label: "점검 관리", group: "admin", koPath: "/admin/external/maintenance", enPath: "/en/admin/external/maintenance" },
  { id: "external-retry", label: "재시도 관리", group: "admin", koPath: "/admin/external/retry", enPath: "/en/admin/external/retry" },
  { id: "security-monitoring", label: "보안 모니터링", group: "admin", koPath: "/admin/system/security-monitoring", enPath: "/en/admin/system/security-monitoring" },
  { id: "blocklist", label: "차단 목록", group: "admin", koPath: "/admin/system/blocklist", enPath: "/en/admin/system/blocklist" },
  { id: "security-audit", label: "보안 감사", group: "admin", koPath: "/admin/system/security-audit", enPath: "/en/admin/system/security-audit" },
  { id: "monitoring-center", label: "운영센터", group: "admin", koPath: "/admin/monitoring/center", enPath: "/en/admin/monitoring/center" },
  { id: "sensor-add", label: "센서 등록", group: "admin", koPath: "/admin/monitoring/sensor_add", enPath: "/en/admin/monitoring/sensor_add" },
  { id: "sensor-edit", label: "센서 설정", group: "admin", koPath: "/admin/monitoring/sensor_edit", enPath: "/en/admin/monitoring/sensor_edit" },
  { id: "sensor-list", label: "센서 목록", group: "admin", koPath: "/admin/monitoring/sensor_list", enPath: "/en/admin/monitoring/sensor_list" },
  { id: "external-connection-add", label: "외부연계 등록", group: "admin", koPath: "/admin/external/connection_add", enPath: "/en/admin/external/connection_add" },
  { id: "external-connection-edit", label: "외부연계 수정", group: "admin", koPath: "/admin/external/connection_edit", enPath: "/en/admin/external/connection_edit" },
  { id: "batch-management", label: "배치 관리", group: "admin", koPath: "/admin/system/batch", enPath: "/en/admin/system/batch" },
  { id: "scheduler-management", label: "스케줄러 관리", group: "admin", koPath: "/admin/system/scheduler", enPath: "/en/admin/system/scheduler" },
  { id: "backup-config", label: "백업 설정", group: "admin", koPath: "/admin/system/backup_config", enPath: "/en/admin/system/backup_config" },
  { id: "backup-execution", label: "백업 실행", group: "admin", koPath: "/admin/system/backup", enPath: "/en/admin/system/backup" },
  { id: "restore-execution", label: "복구 실행", group: "admin", koPath: "/admin/system/restore", enPath: "/en/admin/system/restore" }
] as const satisfies ReadonlyArray<RouteUnitDefinition>;

export type AdminSystemRouteId = (typeof ADMIN_SYSTEM_ROUTE_DEFINITIONS)[number]["id"];
