import type { RouteUnitDefinition } from "../../../framework/routes/pageUnitTypes";

export const EMISSION_MONITORING_ROUTE_DEFINITIONS = [
  { id: "emission-result-list", label: "배출 결과 목록", group: "admin", koPath: "/admin/emission/result_list", enPath: "/en/admin/emission/result_list" },
  { id: "emission-result-detail", label: "결과 상세", group: "admin", koPath: "/admin/emission/result_detail", enPath: "/en/admin/emission/result_detail" },
  { id: "emission-validate", label: "검증 관리", group: "admin", koPath: "/admin/emission/validate", enPath: "/en/admin/emission/validate" },
  { id: "emission-management", label: "배출 변수 관리", group: "admin", koPath: "/admin/emission/management", enPath: "/en/admin/emission/management" },
  { id: "emission-lci-classification", label: "LCI 분류 관리", group: "admin", koPath: "/admin/emission/lci-classification", enPath: "/en/admin/emission/lci-classification" },
  { id: "emission-definition-studio", label: "배출 정의 관리", group: "admin", koPath: "/admin/emission/definition-studio", enPath: "/en/admin/emission/definition-studio" },
  { id: "emission-gwp-values", label: "GWP 값 관리", group: "admin", koPath: "/admin/emission/gwp-values", enPath: "/en/admin/emission/gwp-values" },
  { id: "emission-survey-admin", label: "배출 설문 관리", group: "admin", koPath: "/admin/emission/survey-admin", enPath: "/en/admin/emission/survey-admin" },
  { id: "emission-survey-admin-data", label: "배출 설문 데이터셋", group: "admin", koPath: "/admin/emission/survey-admin-data", enPath: "/en/admin/emission/survey-admin-data" },
  { id: "emission-data-history", label: "데이터 변경 이력", group: "admin", koPath: "/admin/emission/data_history", enPath: "/en/admin/emission/data_history" },
  { id: "emission-site-management", label: "배출지 관리", group: "admin", koPath: "/admin/emission/site-management", enPath: "/en/admin/emission/site-management" },
  { id: "certificate-rec-check", label: "REC 중복 확인", group: "admin", koPath: "/admin/certificate/rec_check", enPath: "/en/admin/certificate/rec_check" },
  { id: "certificate-audit-log", label: "인증서 감사 로그", group: "admin", koPath: "/admin/certificate/audit-log", enPath: "/en/admin/certificate/audit-log" },
  { id: "certificate-objection-list", label: "이의신청 처리", group: "admin", koPath: "/admin/certificate/objection_list", enPath: "/en/admin/certificate/objection_list" },
  { id: "emission-project-list", label: "배출량 관리", group: "home", koPath: "/emission/project_list", enPath: "/en/emission/project_list" },
  { id: "emission-reduction", label: "감축 시나리오", group: "home", koPath: "/emission/reduction", enPath: "/en/emission/reduction" },
  { id: "emission-lci", label: "LCI DB 조회", group: "home", koPath: "/emission/lci", enPath: "/en/emission/lci" },
  { id: "emission-data-input", label: "데이터 입력", group: "home", koPath: "/emission/data_input", enPath: "/en/emission/data_input" },
  { id: "emission-report-submit", label: "배출량 보고서 작성", group: "home", koPath: "/emission/report_submit", enPath: "/en/emission/report_submit" },
  { id: "emission-lca", label: "LCA 분석", group: "home", koPath: "/emission/lca", enPath: "/en/emission/lca" },
  { id: "emission-simulate", label: "시뮬레이션", group: "home", koPath: "/emission/simulate", enPath: "/en/emission/simulate" },
  { id: "monitoring-dashboard", label: "통합 대시보드", group: "home", koPath: "/monitoring/dashboard", enPath: "/en/monitoring/dashboard" },
  { id: "monitoring-realtime", label: "실시간 모니터링", group: "home", koPath: "/monitoring/realtime", enPath: "/en/monitoring/realtime" },
  { id: "monitoring-alerts", label: "경보 현황", group: "home", koPath: "/monitoring/alerts", enPath: "/en/monitoring/alerts" },
  { id: "monitoring-statistics", label: "ESG 보고서", group: "home", koPath: "/monitoring/statistics", enPath: "/en/monitoring/statistics" },
  { id: "monitoring-share", label: "이해관계자 공유", group: "home", koPath: "/monitoring/share", enPath: "/en/monitoring/share" },
  { id: "monitoring-reduction-trend", label: "성과 추이 분석", group: "home", koPath: "/monitoring/reduction_trend", enPath: "/en/monitoring/reduction_trend" },
  { id: "monitoring-track", label: "추적 리포트", group: "home", koPath: "/monitoring/track", enPath: "/en/monitoring/track" },
  { id: "monitoring-export", label: "분석 리포트 내보내기", group: "home", koPath: "/monitoring/export", enPath: "/en/monitoring/export" },
  { id: "co2-production-list", label: "생산 정보", group: "home", koPath: "/co2/production_list", enPath: "/en/co2/production_list" },
  { id: "co2-demand-list", label: "수요 정보", group: "home", koPath: "/co2/demand_list", enPath: "/en/co2/demand_list" },
  { id: "co2-integrity", label: "무결성 추적", group: "home", koPath: "/co2/integrity", enPath: "/en/co2/integrity" },
  { id: "co2-analysis", label: "품질 지표", group: "home", koPath: "/co2/analysis", enPath: "/en/co2/analysis" },
  { id: "co2-search", label: "MRV 정보", group: "home", koPath: "/co2/search", enPath: "/en/co2/search" },
  { id: "emission-home-validate", label: "산정 검증", group: "home", koPath: "/emission/validate", enPath: "/en/emission/validate" }
] as const satisfies ReadonlyArray<RouteUnitDefinition>;

export type EmissionMonitoringRouteId = (typeof EMISSION_MONITORING_ROUTE_DEFINITIONS)[number]["id"];
