import { ComponentType, lazy } from "react";
import type { MigrationPageId } from "./definitions";

function lazyNamed<TModule, TKey extends keyof TModule>(
  loader: () => Promise<TModule>,
  exportName: TKey
) {
  return lazy(async () => {
    const module = await loader();
    return { default: module[exportName] as ComponentType };
  });
}

const sharedPlatformLoader = () => import("../../features/platform-studio/PlatformStudioMigrationPage");
const sharedAdminEntryLoader = () => import("../../features/admin-entry/AdminEntryPages");
const sharedPublicEntryLoader = () => import("../../features/public-entry/PublicEntryPages");
const sharedJoinCompanyStatusLoader = () => import("../../features/join-company-status/JoinCompanyStatusMigrationPage");

export const pageComponents: Record<MigrationPageId, ComponentType> = {
  "home": lazyNamed(() => import("../../features/home-entry/HomeEntryPages"), "HomeLandingPage"),
  "admin-home": lazyNamed(sharedAdminEntryLoader, "AdminHomePage"),
  "signin-login": lazyNamed(sharedPublicEntryLoader, "PublicLoginPage"),
  "admin-login": lazyNamed(sharedAdminEntryLoader, "AdminLoginPage"),
  "signin-auth-choice": lazyNamed(sharedPublicEntryLoader, "AuthChoicePage"),
  "signin-find-id": lazyNamed(sharedPublicEntryLoader, "FindIdPage"),
  "signin-find-id-result": lazyNamed(sharedPublicEntryLoader, "FindIdResultPage"),
  "signin-find-password": lazyNamed(sharedPublicEntryLoader, "FindPasswordPage"),
  "signin-find-password-result": lazyNamed(sharedPublicEntryLoader, "FindPasswordCompletePage"),
  "signin-forbidden": lazyNamed(sharedPublicEntryLoader, "ForbiddenPage"),
  "auth-group": lazyNamed(() => import("../../features/auth-groups/AuthGroupMigrationPage"), "AuthGroupMigrationPage"),
  "auth-change": lazyNamed(() => import("../../features/auth-change/AuthChangeMigrationPage"), "AuthChangeMigrationPage"),
  "dept-role": lazyNamed(() => import("../../features/dept-role-mapping/DeptRoleMappingMigrationPage"), "DeptRoleMappingMigrationPage"),
  "member-edit": lazyNamed(() => import("../../features/member-edit/MemberEditMigrationPage"), "MemberEditMigrationPage"),
  "password-reset": lazyNamed(() => import("../../features/password-reset/PasswordResetMigrationPage"), "PasswordResetMigrationPage"),
  "admin-permission": lazyNamed(() => import("../../features/admin-permissions/AdminPermissionMigrationPage"), "AdminPermissionMigrationPage"),
  "admin-create": lazyNamed(() => import("../../features/admin-account-create/AdminAccountCreateMigrationPage"), "AdminAccountCreateMigrationPage"),
  "company-account": lazyNamed(() => import("../../features/company-account/CompanyAccountMigrationPage"), "CompanyAccountMigrationPage"),
  "admin-list": lazyNamed(() => import("../../features/admin-list/AdminListMigrationPage"), "AdminListMigrationPage"),
  "company-list": lazyNamed(() => import("../../features/company-list/CompanyListMigrationPage"), "CompanyListMigrationPage"),
  "member-approve": lazyNamed(() => import("../../features/member-approve/MemberApproveMigrationPage"), "MemberApproveMigrationPage"),
  "company-approve": lazyNamed(() => import("../../features/company-approve/CompanyApproveMigrationPage"), "CompanyApproveMigrationPage"),
  "certificate-approve": lazyNamed(() => import("../../features/certificate-approve/CertificateApproveMigrationPage"), "CertificateApproveMigrationPage"),
  "certificate-pending": lazyNamed(() => import("../../features/certificate-pending/CertificatePendingMigrationPage"), "CertificatePendingMigrationPage"),
  "virtual-issue": lazyNamed(() => import("../../features/virtual-issue/VirtualIssueMigrationPage"), "VirtualIssueMigrationPage"),
  "member-list": lazyNamed(() => import("../../features/member-list/MemberListMigrationPage"), "MemberListMigrationPage"),
  "member-withdrawn": lazyNamed(() => import("../../features/member-list/MemberListMigrationPage"), "WithdrawnMemberListMigrationPage"),
  "member-activate": lazyNamed(() => import("../../features/member-list/MemberListMigrationPage"), "ActivateMemberListMigrationPage"),
  "member-detail": lazyNamed(() => import("../../features/member-detail/MemberDetailMigrationPage"), "MemberDetailMigrationPage"),
  "company-detail": lazyNamed(() => import("../../features/company-detail/CompanyDetailMigrationPage"), "CompanyDetailMigrationPage"),
  "member-stats": lazyNamed(() => import("../../features/member-stats/MemberStatsMigrationPage"), "MemberStatsMigrationPage"),
  "member-register": lazyNamed(() => import("../../features/member-register/MemberRegisterMigrationPage"), "MemberRegisterMigrationPage"),
  "trade-list": lazyNamed(() => import("../../features/trade-list/TradeListMigrationPage"), "TradeListMigrationPage"),
  "trade-market": lazyNamed(() => import("../../features/trade-market/TradeMarketMigrationPage"), "TradeMarketMigrationPage"),
  "trade-report": lazyNamed(() => import("../../features/trade-report/TradeReportMigrationPage"), "TradeReportMigrationPage"),
  "trade-statistics": lazyNamed(() => import("../../features/trade-statistics/TradeStatisticsMigrationPage"), "TradeStatisticsMigrationPage"),
  "refund-list": lazyNamed(() => import("../../features/refund-list/RefundListMigrationPage"), "RefundListMigrationPage"),
  "settlement-calendar": lazyNamed(() => import("../../features/settlement-calendar/SettlementCalendarMigrationPage"), "SettlementCalendarMigrationPage"),
  "trade-duplicate": lazyNamed(() => import("../../features/trade-duplicate/TradeDuplicateMigrationPage"), "TradeDuplicateMigrationPage"),
  "trade-approve": lazyNamed(() => import("../../features/trade-approve/TradeApproveMigrationPage"), "TradeApproveMigrationPage"),
  "trade-reject": lazyNamed(() => import("../../features/trade-reject/TradeRejectMigrationPage"), "TradeRejectMigrationPage"),
  "refund-process": lazyNamed(() => import("../../features/refund-process/RefundProcessMigrationPage"), "RefundProcessMigrationPage"),
  "certificate-review": lazyNamed(() => import("../../features/certificate-review/CertificateReviewMigrationPage"), "CertificateReviewMigrationPage"),
  "certificate-statistics": lazyNamed(() => import("../../features/certificate-statistics/CertificateStatisticsMigrationPage"), "CertificateStatisticsMigrationPage"),
  "emission-result-list": lazyNamed(() => import("../../features/emission-result-list/EmissionResultListMigrationPage"), "EmissionResultListMigrationPage"),
  "emission-result-detail": lazyNamed(() => import("../../features/emission-result-detail/EmissionResultDetailMigrationPage"), "EmissionResultDetailMigrationPage"),
  "emission-validate": lazyNamed(() => import("../../features/emission-validate/EmissionValidateMigrationPage"), "EmissionValidateMigrationPage"),
  "emission-management": lazyNamed(() => import("../../features/emission-management/EmissionManagementMigrationPage"), "EmissionManagementMigrationPage"),
  "emission-definition-studio": lazyNamed(() => import("../../features/emission-definition-studio"), "EmissionDefinitionStudioMigrationPage"),
  "emission-data-history": lazyNamed(() => import("../../features/emission-data-history/EmissionDataHistoryMigrationPage"), "EmissionDataHistoryMigrationPage"),
  "emission-site-management": lazyNamed(() => import("../../features/emission-site-management/EmissionSiteManagementMigrationPage"), "EmissionSiteManagementMigrationPage"),
  "certificate-rec-check": lazyNamed(() => import("../../features/certificate-rec-check/CertificateRecCheckMigrationPage"), "CertificateRecCheckMigrationPage"),
  "certificate-audit-log": lazyNamed(() => import("../../features/certificate-audit-log/CertificateAuditLogMigrationPage"), "CertificateAuditLogMigrationPage"),
  "certificate-objection-list": lazyNamed(() => import("../../features/certificate-objection-list/CertificateObjectionListMigrationPage"), "CertificateObjectionListMigrationPage"),
  "system-code": lazyNamed(() => import("../../features/system-code/SystemCodeMigrationPage"), "SystemCodeMigrationPage"),
  "page-management": lazyNamed(() => import("../../features/page-management/PageManagementMigrationPage"), "PageManagementMigrationPage"),
  "function-management": lazyNamed(() => import("../../features/function-management/FunctionManagementMigrationPage"), "FunctionManagementMigrationPage"),
  "menu-management": lazyNamed(() => import("../../features/menu-management/MenuManagementMigrationPage"), "MenuManagementMigrationPage"),
  "faq-menu-management": lazyNamed(() => import("../../features/menu-management/FaqMenuManagementMigrationPage"), "FaqMenuManagementMigrationPage"),
  "full-stack-management": lazyNamed(() => import("../../features/menu-management/FullStackManagementMigrationPage"), "FullStackManagementMigrationPage"),
  "infra": lazyNamed(() => import("../../features/system-infra/InfraManagementMigrationPage"), "InfraManagementMigrationPage"),
  "platform-studio": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "screen-elements-management": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "event-management-console": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "function-management-console": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "api-management-console": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "controller-management-console": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "db-table-management": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "column-management-console": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "automation-studio": lazyNamed(sharedPlatformLoader, "PlatformStudioMigrationPage"),
  "environment-management": lazyNamed(() => import("../../features/environment-management/EnvironmentManagementHubPage"), "EnvironmentManagementHubPage"),
  "screen-builder": lazyNamed(() => import("../../features/screen-builder/ScreenBuilderMigrationPage"), "ScreenBuilderMigrationPage"),
  "screen-runtime": lazyNamed(() => import("../../features/screen-builder/ScreenRuntimeMigrationPage"), "ScreenRuntimeMigrationPage"),
  "current-runtime-compare": lazyNamed(() => import("../../features/screen-builder/CurrentRuntimeCompareMigrationPage"), "CurrentRuntimeCompareMigrationPage"),
  "repair-workbench": lazyNamed(() => import("../../features/screen-builder/RepairWorkbenchMigrationPage"), "RepairWorkbenchMigrationPage"),
  "screen-flow-management": lazyNamed(() => import("../../features/screen-management/ScreenFlowManagementMigrationPage"), "ScreenFlowManagementMigrationPage"),
  "screen-menu-assignment-management": lazyNamed(() => import("../../features/screen-management/ScreenMenuAssignmentManagementMigrationPage"), "ScreenMenuAssignmentManagementMigrationPage"),
  "wbs-management": lazyNamed(() => import("../../features/wbs-management/WbsManagementMigrationPage"), "WbsManagementMigrationPage"),
  "new-page": lazyNamed(() => import("../../features/new-page"), "NewPageMigrationPage"),
  "ip-whitelist": lazyNamed(() => import("../../features/ip-whitelist/IpWhitelistMigrationPage"), "IpWhitelistMigrationPage"),
  "access-history": lazyNamed(() => import("../../features/access-history/AccessHistoryMigrationPage"), "AccessHistoryMigrationPage"),
  "error-log": lazyNamed(() => import("../../features/error-log/ErrorLogMigrationPage"), "ErrorLogMigrationPage"),
  "login-history": lazyNamed(() => import("../../features/login-history/LoginHistoryMigrationPage"), "LoginHistoryMigrationPage"),
  "member-security-history": lazyNamed(() => import("../../features/security-history/MemberSecurityHistoryMigrationPage"), "MemberSecurityHistoryMigrationPage"),
  "security-history": lazyNamed(() => import("../../features/security-history/SecurityHistoryMigrationPage"), "SecurityHistoryMigrationPage"),
  "security-policy": lazyNamed(() => import("../../features/security-policy/SecurityPolicyMigrationPage"), "SecurityPolicyMigrationPage"),
  "notification": lazyNamed(() => import("../../features/notification-center/NotificationCenterMigrationPage"), "NotificationCenterMigrationPage"),
  "performance": lazyNamed(() => import("../../features/performance/PerformanceMigrationPage"), "PerformanceMigrationPage"),
  "external-connection-list": lazyNamed(() => import("../../features/external-connection-list/ExternalConnectionListMigrationPage"), "ExternalConnectionListMigrationPage"),
  "external-schema": lazyNamed(() => import("../../features/external-schema/ExternalSchemaMigrationPage"), "ExternalSchemaMigrationPage"),
  "external-keys": lazyNamed(() => import("../../features/external-keys/ExternalKeysMigrationPage"), "ExternalKeysMigrationPage"),
  "external-usage": lazyNamed(() => import("../../features/external-usage/ExternalUsageMigrationPage"), "ExternalUsageMigrationPage"),
  "external-logs": lazyNamed(() => import("../../features/external-logs/ExternalLogsMigrationPage"), "ExternalLogsMigrationPage"),
  "external-webhooks": lazyNamed(() => import("../../features/external-webhooks/ExternalWebhooksMigrationPage"), "ExternalWebhooksMigrationPage"),
  "external-sync": lazyNamed(() => import("../../features/external-sync/ExternalSyncMigrationPage"), "ExternalSyncMigrationPage"),
  "external-monitoring": lazyNamed(() => import("../../features/external-monitoring/ExternalMonitoringMigrationPage"), "ExternalMonitoringMigrationPage"),
  "external-maintenance": lazyNamed(() => import("../../features/external-maintenance/ExternalMaintenanceMigrationPage"), "ExternalMaintenanceMigrationPage"),
  "external-retry": lazyNamed(() => import("../../features/external-retry/ExternalRetryMigrationPage"), "ExternalRetryMigrationPage"),
  "security-monitoring": lazyNamed(() => import("../../features/security-monitoring/SecurityMonitoringMigrationPage"), "SecurityMonitoringMigrationPage"),
  "blocklist": lazyNamed(() => import("../../features/blocklist/BlocklistMigrationPage"), "BlocklistMigrationPage"),
  "security-audit": lazyNamed(() => import("../../features/security-audit/SecurityAuditMigrationPage"), "SecurityAuditMigrationPage"),
  "monitoring-center": lazyNamed(() => import("../../features/operations-center/OperationsCenterMigrationPage"), "OperationsCenterMigrationPage"),
  "sensor-add": lazyNamed(() => import("../../features/sensor-add/SensorAddMigrationPage"), "SensorAddMigrationPage"),
  "sensor-edit": lazyNamed(() => import("../../features/sensor-edit/SensorEditMigrationPage"), "SensorEditMigrationPage"),
  "sensor-list": lazyNamed(() => import("../../features/sensor-list/SensorListMigrationPage"), "SensorListMigrationPage"),
  "external-connection-add": lazyNamed(() => import("../../features/external-connection-add/ExternalConnectionAddMigrationPage"), "ExternalConnectionAddMigrationPage"),
  "external-connection-edit": lazyNamed(() => import("../../features/external-connection-edit/ExternalConnectionEditMigrationPage"), "ExternalConnectionEditMigrationPage"),
  "batch-management": lazyNamed(() => import("../../features/batch-management/BatchManagementMigrationPage"), "BatchManagementMigrationPage"),
  "scheduler-management": lazyNamed(() => import("../../features/scheduler-management/SchedulerManagementMigrationPage"), "SchedulerManagementMigrationPage"),
  "backup-config": lazyNamed(() => import("../../features/backup-config/BackupConfigMigrationPage"), "BackupConfigMigrationPage"),
  "backup-execution": lazyNamed(() => import("../../features/backup-config/BackupConfigMigrationPage"), "BackupConfigMigrationPage"),
  "restore-execution": lazyNamed(() => import("../../features/backup-config/BackupConfigMigrationPage"), "BackupConfigMigrationPage"),
  "version-management": lazyNamed(() => import("../../features/backup-config/BackupConfigMigrationPage"), "BackupConfigMigrationPage"),
  "codex-request": lazyNamed(() => import("../../features/codex-provision/CodexProvisionMigrationPage"), "CodexProvisionMigrationPage"),
  "unified-log": lazyNamed(() => import("../../features/observability/ObservabilityMigrationPage"), "ObservabilityMigrationPage"),
  "observability": lazyNamed(() => import("../../features/observability/ObservabilityMigrationPage"), "ObservabilityMigrationPage"),
  "help-management": lazyNamed(() => import("../../features/help-management/HelpManagementMigrationPage"), "HelpManagementMigrationPage"),
  "sr-workbench": lazyNamed(() => import("../../features/sr-workbench/SrWorkbenchMigrationPage"), "SrWorkbenchMigrationPage"),
  "board-list": lazyNamed(() => import("../../features/board-list/BoardListMigrationPage"), "BoardListMigrationPage"),
  "board-add": lazyNamed(() => import("../../features/board-add/BoardAddMigrationPage"), "BoardAddMigrationPage"),
  "post-list": lazyNamed(() => import("../../features/post-list/PostListMigrationPage"), "PostListMigrationPage"),
  "banner-list": lazyNamed(() => import("../../features/banner-list/BannerListMigrationPage"), "BannerListMigrationPage"),
  "popup-list": lazyNamed(() => import("../../features/popup-list/PopupListMigrationPage"), "PopupListMigrationPage"),
  "banner-edit": lazyNamed(() => import("../../features/banner-edit/BannerEditMigrationPage"), "BannerEditMigrationPage"),
  "popup-edit": lazyNamed(() => import("../../features/popup-edit/PopupEditMigrationPage"), "PopupEditMigrationPage"),
  "qna-category": lazyNamed(() => import("../../features/qna-category/QnaCategoryMigrationPage"), "QnaCategoryMigrationPage"),
  "faq-management": lazyNamed(() => import("../../features/faq-management/FaqManagementMigrationPage"), "FaqManagementMigrationPage"),
  "file-management": lazyNamed(() => import("../../features/file-management/FileManagementMigrationPage"), "FileManagementMigrationPage"),
  "admin-sitemap": lazyNamed(() => import("../../features/admin-sitemap/AdminSitemapMigrationPage"), "AdminSitemapMigrationPage"),
  "tag-management": lazyNamed(() => import("../../features/tag-management/TagManagementMigrationPage"), "TagManagementMigrationPage"),
  "admin-menu-placeholder": lazyNamed(() => import("../../features/admin-placeholder/AdminMenuPlaceholderPage"), "AdminMenuPlaceholderPage"),
  "emission-project-list": lazyNamed(() => import("../../features/emission-project-list/EmissionProjectListMigrationPage"), "EmissionProjectListMigrationPage"),
  "emission-reduction": lazyNamed(() => import("../../features/emission-reduction/EmissionReductionMigrationPage"), "EmissionReductionMigrationPage"),
  "emission-lci": lazyNamed(() => import("../../features/emission-lci/EmissionLciMigrationPage"), "EmissionLciMigrationPage"),
  "emission-data-input": lazyNamed(() => import("../../features/emission-data-input/EmissionDataInputMigrationPage"), "EmissionDataInputMigrationPage"),
  "emission-report-submit": lazyNamed(() => import("../../features/emission-report-submit/EmissionReportSubmitMigrationPage"), "EmissionReportSubmitMigrationPage"),
  "emission-lca": lazyNamed(() => import("../../features/emission-lca/EmissionLcaMigrationPage"), "EmissionLcaMigrationPage"),
  "emission-simulate": lazyNamed(() => import("../../features/emission-simulate/EmissionSimulateMigrationPage"), "EmissionSimulateMigrationPage"),
  "monitoring-dashboard": lazyNamed(() => import("../../features/monitoring-dashboard/MonitoringDashboardMigrationPage"), "MonitoringDashboardMigrationPage"),
  "monitoring-realtime": lazyNamed(() => import("../../features/monitoring-dashboard/MonitoringRealtimeMigrationPage"), "MonitoringRealtimeMigrationPage"),
  "monitoring-alerts": lazyNamed(() => import("../../features/monitoring-dashboard/MonitoringAlertsMigrationPage"), "MonitoringAlertsMigrationPage"),
  "monitoring-statistics": lazyNamed(() => import("../../features/monitoring-statistics/MonitoringStatisticsMigrationPage"), "MonitoringStatisticsMigrationPage"),
  "monitoring-share": lazyNamed(() => import("../../features/monitoring-share/MonitoringShareMigrationPage"), "MonitoringShareMigrationPage"),
  "monitoring-reduction-trend": lazyNamed(() => import("../../features/monitoring-reduction-trend/MonitoringReductionTrendMigrationPage"), "MonitoringReductionTrendMigrationPage"),
  "monitoring-track": lazyNamed(() => import("../../features/monitoring-track/MonitoringTrackMigrationPage"), "MonitoringTrackMigrationPage"),
  "monitoring-export": lazyNamed(() => import("../../features/monitoring-export/MonitoringExportMigrationPage"), "MonitoringExportMigrationPage"),
  "co2-production-list": lazyNamed(() => import("../../features/co2-production-list/Co2ProductionListMigrationPage"), "Co2ProductionListMigrationPage"),
  "co2-demand-list": lazyNamed(() => import("../../features/co2-demand-list/Co2DemandListMigrationPage"), "Co2DemandListMigrationPage"),
  "co2-integrity": lazyNamed(() => import("../../features/co2-integrity/Co2IntegrityMigrationPage"), "Co2IntegrityMigrationPage"),
  "co2-credit": lazyNamed(() => import("../../features/co2-credit/Co2CreditMigrationPage"), "Co2CreditMigrationPage"),
  "co2-analysis": lazyNamed(() => import("../../features/co2-analysis/Co2AnalysisMigrationPage"), "Co2AnalysisMigrationPage"),
  "co2-search": lazyNamed(() => import("../../features/co2-search/Co2SearchMigrationPage"), "Co2SearchMigrationPage"),
  "trade-buy-request": lazyNamed(() => import("../../features/trade-buy-request/TradeBuyRequestMigrationPage"), "TradeBuyRequestMigrationPage"),
  "trade-complete": lazyNamed(() => import("../../features/trade-complete/TradeCompleteMigrationPage"), "TradeCompleteMigrationPage"),
  "trade-auto-order": lazyNamed(() => import("../../features/trade-auto-order/TradeAutoOrderMigrationPage"), "TradeAutoOrderMigrationPage"),
  "trade-sell": lazyNamed(() => import("../../features/trade-sell/TradeSellMigrationPage"), "TradeSellMigrationPage"),
  "trade-price-alert": lazyNamed(() => import("../../features/trade-price-alert/TradePriceAlertMigrationPage"), "TradePriceAlertMigrationPage"),
  "payment-pay": lazyNamed(() => import("../../features/payment-pay/PaymentPayMigrationPage"), "PaymentPayMigrationPage"),
  "payment-virtual-account": lazyNamed(() => import("../../features/payment-virtual-account/PaymentVirtualAccountMigrationPage"), "PaymentVirtualAccountMigrationPage"),
  "payment-refund": lazyNamed(() => import("../../features/payment-refund/PaymentRefundMigrationPage"), "PaymentRefundMigrationPage"),
  "payment-refund-account": lazyNamed(() => import("../../features/payment-refund-account/PaymentRefundAccountMigrationPage"), "PaymentRefundAccountMigrationPage"),
  "payment-notify": lazyNamed(() => import("../../features/payment-notify/PaymentNotifyMigrationPage"), "PaymentNotifyMigrationPage"),
  "payment-receipt": lazyNamed(() => import("../../features/payment-receipt/PaymentReceiptMigrationPage"), "PaymentReceiptMigrationPage"),
  "emission-home-validate": lazyNamed(() => import("../../features/emission-home-validate/EmissionHomeValidateMigrationPage"), "EmissionHomeValidateMigrationPage"),
  "certificate-list": lazyNamed(() => import("../../features/certificate-list/CertificateListMigrationPage"), "CertificateListMigrationPage"),
  "certificate-apply": lazyNamed(() => import("../../features/certificate-apply/CertificateApplyMigrationPage"), "CertificateApplyMigrationPage"),
  "certificate-report-list": lazyNamed(() => import("../../features/certificate-report-list/CertificateReportListMigrationPage"), "CertificateReportListMigrationPage"),
  "certificate-report-form": lazyNamed(() => import("../../features/certificate-report-form/CertificateReportFormMigrationPage"), "CertificateReportFormMigrationPage"),
  "certificate-report-edit": lazyNamed(() => import("../../features/certificate-report-edit/CertificateReportEditMigrationPage"), "CertificateReportEditMigrationPage"),
  "payment-history": lazyNamed(() => import("../../features/payment-history/PaymentHistoryMigrationPage"), "PaymentHistoryMigrationPage"),
  "edu-course-list": lazyNamed(() => import("../../features/edu-course-list/EduCourseListMigrationPage"), "EduCourseListMigrationPage"),
  "edu-my-course": lazyNamed(() => import("../../features/edu-my-course/EduMyCourseMigrationPage"), "EduMyCourseMigrationPage"),
  "edu-progress": lazyNamed(() => import("../../features/edu-progress/EduProgressMigrationPage"), "EduProgressMigrationPage"),
  "edu-content": lazyNamed(() => import("../../features/edu-content/EduContentMigrationPage"), "EduContentMigrationPage"),
  "edu-course-detail": lazyNamed(() => import("../../features/edu-course-detail/EduCourseDetailMigrationPage"), "EduCourseDetailMigrationPage"),
  "edu-apply": lazyNamed(() => import("../../features/edu-apply/EduApplyMigrationPage"), "EduApplyMigrationPage"),
  "edu-survey": lazyNamed(() => import("../../features/edu-survey/EduSurveyMigrationPage"), "EduSurveyMigrationPage"),
  "edu-certificate": lazyNamed(() => import("../../features/edu-certificate/EduCertificateMigrationPage"), "EduCertificateMigrationPage"),
  "join-company-register": lazyNamed(() => import("../../features/join-company-register/JoinCompanyRegisterMigrationPage"), "JoinCompanyRegisterMigrationPage"),
  "join-company-register-complete": lazyNamed(() => import("../../features/join-company-register/JoinCompanyRegisterCompleteMigrationPage"), "JoinCompanyRegisterCompleteMigrationPage"),
  "join-company-status": lazyNamed(sharedJoinCompanyStatusLoader, "JoinCompanyStatusMigrationPage"),
  "join-company-status-guide": lazyNamed(sharedJoinCompanyStatusLoader, "JoinCompanyStatusMigrationPage"),
  "join-company-status-detail": lazyNamed(sharedJoinCompanyStatusLoader, "JoinCompanyStatusMigrationPage"),
  "join-company-reapply": lazyNamed(() => import("../../features/join-company-reapply/JoinCompanyReapplyMigrationPage"), "JoinCompanyReapplyMigrationPage"),
  "my-inquiry": lazyNamed(() => import("../../features/my-inquiry/MyInquiryMigrationPage"), "MyInquiryMigrationPage"),
  "support-faq": lazyNamed(() => import("../../features/support-faq/SupportFaqMigrationPage"), "SupportFaqMigrationPage"),
  "support-inquiry": lazyNamed(() => import("../../features/support-inquiry/SupportInquiryMigrationPage"), "SupportInquiryMigrationPage"),
  "join-wizard": lazyNamed(() => import("../../features/join-wizard/JoinWizardMigrationPage"), "JoinWizardMigrationPage"),
  "join-terms": lazyNamed(() => import("../../features/join-wizard/JoinTermsMigrationPage"), "JoinTermsMigrationPage"),
  "join-auth": lazyNamed(() => import("../../features/join-wizard/JoinAuthMigrationPage"), "JoinAuthMigrationPage"),
  "join-info": lazyNamed(() => import("../../features/join-wizard/JoinInfoMigrationPage"), "JoinInfoMigrationPage"),
  "join-complete": lazyNamed(() => import("../../features/join-wizard/JoinCompleteMigrationPage"), "JoinCompleteMigrationPage"),
  "mypage": lazyNamed(() => import("../../features/mypage/MypageMigrationPage"), "MypageMigrationPage"),
  "mypage-email": lazyNamed(() => import("../../features/mypage-email/MypageEmailMigrationPage"), "MypageEmailMigrationPage"),
  "mypage-notification": lazyNamed(() => import("../../features/mypage/MypageNotificationMigrationPage"), "MypageNotificationMigrationPage"),
  "mypage-marketing": lazyNamed(() => import("../../features/mypage/MypageMarketingMigrationPage"), "MypageMarketingMigrationPage"),
  "mypage-company": lazyNamed(() => import("../../features/mypage-company/MypageCompanyMigrationPage"), "MypageCompanyMigrationPage"),
  "mypage-password": lazyNamed(() => import("../../features/mypage-password/MypagePasswordMigrationPage"), "MypagePasswordMigrationPage"),
  "mypage-staff": lazyNamed(() => import("../../features/mypage-staff/MypageStaffMigrationPage"), "MypageStaffMigrationPage"),
  "download-list": lazyNamed(() => import("../../features/download-list"), "DownloadListMigrationPage"),
  "notice-list": lazyNamed(() => import("../../features/notice-list"), "NoticeListMigrationPage"),
  "qna-list": lazyNamed(() => import("../../features/qna-list"), "QnaListMigrationPage"),
  "sitemap": lazyNamed(() => import("../../features/sitemap/SitemapMigrationPage"), "SitemapMigrationPage"),
  "home-menu-placeholder": lazyNamed(() => import("../../features/home-placeholder/HomeMenuPlaceholderPage"), "HomeMenuPlaceholderPage")
};

const preloadedModules: Partial<Record<MigrationPageId, Promise<unknown>>> = {};

const pagePreloaders: Partial<Record<MigrationPageId, () => Promise<unknown>>> = {
  "admin-home": sharedAdminEntryLoader,
  "admin-login": sharedAdminEntryLoader,
  "auth-group": () => import("../../features/auth-groups/AuthGroupMigrationPage"),
  "auth-change": () => import("../../features/auth-change/AuthChangeMigrationPage"),
  "dept-role": () => import("../../features/dept-role-mapping/DeptRoleMappingMigrationPage"),
  "member-edit": () => import("../../features/member-edit/MemberEditMigrationPage"),
  "password-reset": () => import("../../features/password-reset/PasswordResetMigrationPage"),
  "admin-permission": () => import("../../features/admin-permissions/AdminPermissionMigrationPage"),
  "admin-create": () => import("../../features/admin-account-create/AdminAccountCreateMigrationPage"),
  "company-account": () => import("../../features/company-account/CompanyAccountMigrationPage"),
  "admin-list": () => import("../../features/admin-list/AdminListMigrationPage"),
  "company-list": () => import("../../features/company-list/CompanyListMigrationPage"),
  "member-approve": () => import("../../features/member-approve/MemberApproveMigrationPage"),
  "company-approve": () => import("../../features/company-approve/CompanyApproveMigrationPage"),
  "certificate-approve": () => import("../../features/certificate-approve/CertificateApproveMigrationPage"),
  "certificate-pending": () => import("../../features/certificate-pending/CertificatePendingMigrationPage"),
  "virtual-issue": () => import("../../features/virtual-issue/VirtualIssueMigrationPage"),
  "member-list": () => import("../../features/member-list/MemberListMigrationPage"),
  "member-withdrawn": () => import("../../features/member-list/MemberListMigrationPage"),
  "member-activate": () => import("../../features/member-list/MemberListMigrationPage"),
  "member-detail": () => import("../../features/member-detail/MemberDetailMigrationPage"),
  "company-detail": () => import("../../features/company-detail/CompanyDetailMigrationPage"),
  "member-stats": () => import("../../features/member-stats/MemberStatsMigrationPage"),
  "member-register": () => import("../../features/member-register/MemberRegisterMigrationPage"),
  "trade-list": () => import("../../features/trade-list/TradeListMigrationPage"),
  "trade-market": () => import("../../features/trade-market/TradeMarketMigrationPage"),
  "trade-report": () => import("../../features/trade-report/TradeReportMigrationPage"),
  "trade-statistics": () => import("../../features/trade-statistics/TradeStatisticsMigrationPage"),
  "refund-list": () => import("../../features/refund-list/RefundListMigrationPage"),
  "settlement-calendar": () => import("../../features/settlement-calendar/SettlementCalendarMigrationPage"),
  "trade-duplicate": () => import("../../features/trade-duplicate/TradeDuplicateMigrationPage"),
  "trade-approve": () => import("../../features/trade-approve/TradeApproveMigrationPage"),
  "trade-reject": () => import("../../features/trade-reject/TradeRejectMigrationPage"),
  "refund-process": () => import("../../features/refund-process/RefundProcessMigrationPage"),
  "certificate-review": () => import("../../features/certificate-review/CertificateReviewMigrationPage"),
  "certificate-statistics": () => import("../../features/certificate-statistics/CertificateStatisticsMigrationPage"),
  "emission-result-list": () => import("../../features/emission-result-list/EmissionResultListMigrationPage"),
  "emission-result-detail": () => import("../../features/emission-result-detail/EmissionResultDetailMigrationPage"),
  "emission-management": () => import("../../features/emission-management/EmissionManagementMigrationPage"),
  "emission-definition-studio": () => import("../../features/emission-definition-studio"),
  "emission-data-history": () => import("../../features/emission-data-history/EmissionDataHistoryMigrationPage"),
  "emission-validate": () => import("../../features/emission-validate/EmissionValidateMigrationPage"),
  "emission-site-management": () => import("../../features/emission-site-management/EmissionSiteManagementMigrationPage"),
  "certificate-rec-check": () => import("../../features/certificate-rec-check/CertificateRecCheckMigrationPage"),
  "certificate-audit-log": () => import("../../features/certificate-audit-log/CertificateAuditLogMigrationPage"),
  "certificate-objection-list": () => import("../../features/certificate-objection-list/CertificateObjectionListMigrationPage"),
  "system-code": () => import("../../features/system-code/SystemCodeMigrationPage"),
  "page-management": () => import("../../features/page-management/PageManagementMigrationPage"),
  "function-management": () => import("../../features/function-management/FunctionManagementMigrationPage"),
  "menu-management": () => import("../../features/menu-management/MenuManagementMigrationPage"),
  "faq-menu-management": () => import("../../features/menu-management/FaqMenuManagementMigrationPage"),
  "full-stack-management": () => import("../../features/menu-management/FullStackManagementMigrationPage"),
  "infra": () => import("../../features/system-infra/InfraManagementMigrationPage"),
  "platform-studio": sharedPlatformLoader,
  "screen-elements-management": sharedPlatformLoader,
  "event-management-console": sharedPlatformLoader,
  "function-management-console": sharedPlatformLoader,
  "api-management-console": sharedPlatformLoader,
  "controller-management-console": sharedPlatformLoader,
  "db-table-management": sharedPlatformLoader,
  "column-management-console": sharedPlatformLoader,
  "automation-studio": sharedPlatformLoader,
  "environment-management": () => import("../../features/environment-management/EnvironmentManagementHubPage"),
  "screen-builder": () => import("../../features/screen-builder/ScreenBuilderMigrationPage"),
  "screen-runtime": () => import("../../features/screen-builder/ScreenRuntimeMigrationPage"),
  "current-runtime-compare": () => import("../../features/screen-builder/CurrentRuntimeCompareMigrationPage"),
  "repair-workbench": () => import("../../features/screen-builder/RepairWorkbenchMigrationPage"),
  "screen-flow-management": () => import("../../features/screen-management/ScreenFlowManagementMigrationPage"),
  "screen-menu-assignment-management": () => import("../../features/screen-management/ScreenMenuAssignmentManagementMigrationPage"),
  "wbs-management": () => import("../../features/wbs-management/WbsManagementMigrationPage"),
  "new-page": () => import("../../features/new-page"),
  "ip-whitelist": () => import("../../features/ip-whitelist/IpWhitelistMigrationPage"),
  "access-history": () => import("../../features/access-history/AccessHistoryMigrationPage"),
  "error-log": () => import("../../features/error-log/ErrorLogMigrationPage"),
  "login-history": () => import("../../features/login-history/LoginHistoryMigrationPage"),
  "member-security-history": () => import("../../features/security-history/MemberSecurityHistoryMigrationPage"),
  "security-history": () => import("../../features/security-history/SecurityHistoryMigrationPage"),
  "security-policy": () => import("../../features/security-policy/SecurityPolicyMigrationPage"),
  "help-management": () => import("../../features/help-management/HelpManagementMigrationPage"),
  "notification": () => import("../../features/notification-center/NotificationCenterMigrationPage"),
  "performance": () => import("../../features/performance/PerformanceMigrationPage"),
  "external-connection-list": () => import("../../features/external-connection-list/ExternalConnectionListMigrationPage"),
  "external-schema": () => import("../../features/external-schema/ExternalSchemaMigrationPage"),
  "external-keys": () => import("../../features/external-keys/ExternalKeysMigrationPage"),
  "external-usage": () => import("../../features/external-usage/ExternalUsageMigrationPage"),
  "external-logs": () => import("../../features/external-logs/ExternalLogsMigrationPage"),
  "external-webhooks": () => import("../../features/external-webhooks/ExternalWebhooksMigrationPage"),
  "external-sync": () => import("../../features/external-sync/ExternalSyncMigrationPage"),
  "external-monitoring": () => import("../../features/external-monitoring/ExternalMonitoringMigrationPage"),
  "external-maintenance": () => import("../../features/external-maintenance/ExternalMaintenanceMigrationPage"),
  "external-retry": () => import("../../features/external-retry/ExternalRetryMigrationPage"),
  "security-monitoring": () => import("../../features/security-monitoring/SecurityMonitoringMigrationPage"),
  "blocklist": () => import("../../features/blocklist/BlocklistMigrationPage"),
  "security-audit": () => import("../../features/security-audit/SecurityAuditMigrationPage"),
  "monitoring-center": () => import("../../features/operations-center/OperationsCenterMigrationPage"),
  "sensor-add": () => import("../../features/sensor-add/SensorAddMigrationPage"),
  "sensor-edit": () => import("../../features/sensor-edit/SensorEditMigrationPage"),
  "sensor-list": () => import("../../features/sensor-list/SensorListMigrationPage"),
  "external-connection-add": () => import("../../features/external-connection-add/ExternalConnectionAddMigrationPage"),
  "external-connection-edit": () => import("../../features/external-connection-edit/ExternalConnectionEditMigrationPage"),
  "scheduler-management": () => import("../../features/scheduler-management/SchedulerManagementMigrationPage"),
  "backup-config": () => import("../../features/backup-config/BackupConfigMigrationPage"),
  "backup-execution": () => import("../../features/backup-config/BackupConfigMigrationPage"),
  "restore-execution": () => import("../../features/backup-config/BackupConfigMigrationPage"),
  "version-management": () => import("../../features/backup-config/BackupConfigMigrationPage"),
  "unified-log": () => import("../../features/observability/ObservabilityMigrationPage"),
  "board-list": () => import("../../features/board-list/BoardListMigrationPage"),
  "board-add": () => import("../../features/board-add/BoardAddMigrationPage"),
  "post-list": () => import("../../features/post-list/PostListMigrationPage"),
  "banner-list": () => import("../../features/banner-list/BannerListMigrationPage"),
  "popup-list": () => import("../../features/popup-list/PopupListMigrationPage"),
  "banner-edit": () => import("../../features/banner-edit/BannerEditMigrationPage"),
  "popup-edit": () => import("../../features/popup-edit/PopupEditMigrationPage"),
  "qna-category": () => import("../../features/qna-category/QnaCategoryMigrationPage"),
  "faq-management": () => import("../../features/faq-management/FaqManagementMigrationPage"),
  "file-management": () => import("../../features/file-management/FileManagementMigrationPage"),
  "admin-sitemap": () => import("../../features/admin-sitemap/AdminSitemapMigrationPage"),
  "tag-management": () => import("../../features/tag-management/TagManagementMigrationPage"),
  "admin-menu-placeholder": () => import("../../features/admin-placeholder/AdminMenuPlaceholderPage"),
  "emission-project-list": () => import("../../features/emission-project-list/EmissionProjectListMigrationPage"),
  "emission-reduction": () => import("../../features/emission-reduction/EmissionReductionMigrationPage"),
  "emission-lci": () => import("../../features/emission-lci/EmissionLciMigrationPage"),
  "emission-data-input": () => import("../../features/emission-data-input/EmissionDataInputMigrationPage"),
  "emission-report-submit": () => import("../../features/emission-report-submit/EmissionReportSubmitMigrationPage"),
  "emission-lca": () => import("../../features/emission-lca/EmissionLcaMigrationPage"),
  "emission-simulate": () => import("../../features/emission-simulate/EmissionSimulateMigrationPage"),
  "monitoring-dashboard": () => import("../../features/monitoring-dashboard/MonitoringDashboardMigrationPage"),
  "monitoring-realtime": () => import("../../features/monitoring-dashboard/MonitoringRealtimeMigrationPage"),
  "monitoring-alerts": () => import("../../features/monitoring-dashboard/MonitoringAlertsMigrationPage"),
  "monitoring-statistics": () => import("../../features/monitoring-statistics/MonitoringStatisticsMigrationPage"),
  "monitoring-share": () => import("../../features/monitoring-share/MonitoringShareMigrationPage"),
  "monitoring-reduction-trend": () => import("../../features/monitoring-reduction-trend/MonitoringReductionTrendMigrationPage"),
  "monitoring-track": () => import("../../features/monitoring-track/MonitoringTrackMigrationPage"),
  "monitoring-export": () => import("../../features/monitoring-export/MonitoringExportMigrationPage"),
  "co2-production-list": () => import("../../features/co2-production-list/Co2ProductionListMigrationPage"),
  "co2-demand-list": () => import("../../features/co2-demand-list/Co2DemandListMigrationPage"),
  "co2-integrity": () => import("../../features/co2-integrity/Co2IntegrityMigrationPage"),
  "co2-credit": () => import("../../features/co2-credit/Co2CreditMigrationPage"),
  "co2-analysis": () => import("../../features/co2-analysis/Co2AnalysisMigrationPage"),
  "co2-search": () => import("../../features/co2-search/Co2SearchMigrationPage"),
  "trade-buy-request": () => import("../../features/trade-buy-request/TradeBuyRequestMigrationPage"),
  "trade-complete": () => import("../../features/trade-complete/TradeCompleteMigrationPage"),
  "trade-auto-order": () => import("../../features/trade-auto-order/TradeAutoOrderMigrationPage"),
  "trade-sell": () => import("../../features/trade-sell/TradeSellMigrationPage"),
  "trade-price-alert": () => import("../../features/trade-price-alert/TradePriceAlertMigrationPage"),
  "payment-pay": () => import("../../features/payment-pay/PaymentPayMigrationPage"),
  "payment-virtual-account": () => import("../../features/payment-virtual-account/PaymentVirtualAccountMigrationPage"),
  "payment-refund": () => import("../../features/payment-refund/PaymentRefundMigrationPage"),
  "payment-refund-account": () => import("../../features/payment-refund-account/PaymentRefundAccountMigrationPage"),
  "payment-notify": () => import("../../features/payment-notify/PaymentNotifyMigrationPage"),
  "payment-receipt": () => import("../../features/payment-receipt/PaymentReceiptMigrationPage"),
  "emission-home-validate": () => import("../../features/emission-home-validate/EmissionHomeValidateMigrationPage"),
  "certificate-list": () => import("../../features/certificate-list/CertificateListMigrationPage"),
  "certificate-apply": () => import("../../features/certificate-apply/CertificateApplyMigrationPage"),
  "certificate-report-list": () => import("../../features/certificate-report-list/CertificateReportListMigrationPage"),
  "certificate-report-form": () => import("../../features/certificate-report-form/CertificateReportFormMigrationPage"),
  "certificate-report-edit": () => import("../../features/certificate-report-edit/CertificateReportEditMigrationPage"),
  "payment-history": () => import("../../features/payment-history/PaymentHistoryMigrationPage"),
  "edu-course-list": () => import("../../features/edu-course-list/EduCourseListMigrationPage"),
  "edu-my-course": () => import("../../features/edu-my-course/EduMyCourseMigrationPage"),
  "edu-progress": () => import("../../features/edu-progress/EduProgressMigrationPage"),
  "edu-content": () => import("../../features/edu-content/EduContentMigrationPage"),
  "edu-course-detail": () => import("../../features/edu-course-detail/EduCourseDetailMigrationPage"),
  "edu-apply": () => import("../../features/edu-apply/EduApplyMigrationPage"),
  "edu-survey": () => import("../../features/edu-survey/EduSurveyMigrationPage"),
  "edu-certificate": () => import("../../features/edu-certificate/EduCertificateMigrationPage"),
  "my-inquiry": () => import("../../features/my-inquiry/MyInquiryMigrationPage"),
  "support-faq": () => import("../../features/support-faq/SupportFaqMigrationPage"),
  "support-inquiry": () => import("../../features/support-inquiry/SupportInquiryMigrationPage"),
  "mypage-email": () => import("../../features/mypage-email/MypageEmailMigrationPage"),
  "mypage-notification": () => import("../../features/mypage/MypageNotificationMigrationPage"),
  "mypage-marketing": () => import("../../features/mypage/MypageMarketingMigrationPage"),
  "download-list": () => import("../../features/download-list"),
  "mypage-password": () => import("../../features/mypage-password/MypagePasswordMigrationPage"),
  "mypage-staff": () => import("../../features/mypage-staff/MypageStaffMigrationPage"),
  "notice-list": () => import("../../features/notice-list"),
  "qna-list": () => import("../../features/qna-list"),
  "sitemap": () => import("../../features/sitemap/SitemapMigrationPage"),
  "home-menu-placeholder": () => import("../../features/home-placeholder/HomeMenuPlaceholderPage")
};

export function getPageComponent(route: MigrationPageId): ComponentType {
  return pageComponents[route] || pageComponents.home;
}

export function preloadPageModule(route: MigrationPageId) {
  const loader = pagePreloaders[route];
  if (!loader) {
    return Promise.resolve();
  }
  if (!preloadedModules[route]) {
    preloadedModules[route] = loader();
  }
  return preloadedModules[route]!;
}
